//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistradorPontoWeb.Models.Ponto
{
    using System;
    using System.Collections.Generic;
    
    public partial class AFD
    {
        public int Id { get; set; }
        public Nullable<int> Codigo { get; set; }
        public Nullable<System.DateTime> Incdata { get; set; }
        public Nullable<System.DateTime> Inchora { get; set; }
        public string Incusuario { get; set; }
        public Nullable<System.DateTime> Altdata { get; set; }
        public Nullable<System.DateTime> Althora { get; set; }
        public string Altusuario { get; set; }
        public string LinhaAFD { get; set; }
        public string OrgaoFiscalizador { get; set; }
        public short Situacao { get; set; }
        public string Observacao { get; set; }
        public Nullable<System.Guid> Identificador { get; set; }
        public string Lote { get; set; }
        public string IpDnsRep { get; set; }
        public string Campo01 { get; set; }
        public string Campo02 { get; set; }
        public string Campo03 { get; set; }
        public string Campo04 { get; set; }
        public string Campo05 { get; set; }
        public string Campo06 { get; set; }
        public string Campo07 { get; set; }
        public string Campo08 { get; set; }
        public string Campo09 { get; set; }
        public string Campo10 { get; set; }
        public string Campo11 { get; set; }
        public string Campo12 { get; set; }
        public Nullable<int> Nsr { get; set; }
        public string Relogio { get; set; }
        public Nullable<System.DateTime> DataHora { get; set; }
    }
}
