//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistradorPontoWeb.Models.Ponto
{
    using System;
    using System.Collections.Generic;
    
    public partial class bancohoras
    {
        public int id { get; set; }
        public int codigo { get; set; }
        public Nullable<int> tipo { get; set; }
        public Nullable<int> identificacao { get; set; }
        public Nullable<System.DateTime> datainicial { get; set; }
        public Nullable<System.DateTime> datafinal { get; set; }
        public Nullable<int> dias_1 { get; set; }
        public Nullable<int> dias_2 { get; set; }
        public Nullable<int> dias_3 { get; set; }
        public Nullable<int> dias_4 { get; set; }
        public Nullable<int> dias_5 { get; set; }
        public Nullable<int> dias_6 { get; set; }
        public Nullable<int> dias_7 { get; set; }
        public Nullable<int> dias_8 { get; set; }
        public Nullable<int> dias_9 { get; set; }
        public Nullable<int> dias_10 { get; set; }
        public Nullable<int> bancoprimeiro { get; set; }
        public string limitehoras_1 { get; set; }
        public string limitehoras_2 { get; set; }
        public string limitehoras_3 { get; set; }
        public string limitehoras_4 { get; set; }
        public string limitehoras_5 { get; set; }
        public string limitehoras_6 { get; set; }
        public string limitehoras_7 { get; set; }
        public string limitehoras_8 { get; set; }
        public string limitehoras_9 { get; set; }
        public string limitehoras_10 { get; set; }
        public Nullable<int> extraprimeiro { get; set; }
        public string limitehorasextras_1 { get; set; }
        public string limitehorasextras_2 { get; set; }
        public string limitehorasextras_3 { get; set; }
        public string limitehorasextras_4 { get; set; }
        public string limitehorasextras_5 { get; set; }
        public string limitehorasextras_6 { get; set; }
        public string limitehorasextras_7 { get; set; }
        public string limitehorasextras_8 { get; set; }
        public string limitehorasextras_9 { get; set; }
        public string limitehorasextras_10 { get; set; }
        public Nullable<short> percentuais_1 { get; set; }
        public Nullable<short> percentuais_2 { get; set; }
        public Nullable<short> percentuais_3 { get; set; }
        public Nullable<short> percentuais_4 { get; set; }
        public Nullable<short> percentuais_5 { get; set; }
        public Nullable<short> percentuais_6 { get; set; }
        public Nullable<short> percentuais_7 { get; set; }
        public Nullable<short> percentuais_8 { get; set; }
        public Nullable<short> percentuais_9 { get; set; }
        public Nullable<short> percentuais_10 { get; set; }
        public Nullable<System.DateTime> incdata { get; set; }
        public Nullable<System.DateTime> inchora { get; set; }
        public string incusuario { get; set; }
        public Nullable<System.DateTime> altdata { get; set; }
        public Nullable<System.DateTime> althora { get; set; }
        public string altusuario { get; set; }
        public bool perccomohoraextra { get; set; }
        public bool bancohorasacumulativo { get; set; }
        public bool limite_1 { get; set; }
        public bool limite_2 { get; set; }
        public bool limite_3 { get; set; }
        public bool limite_4 { get; set; }
        public bool limite_5 { get; set; }
        public bool limite_6 { get; set; }
        public int limitepcthoras_1 { get; set; }
        public int limitepcthoras_2 { get; set; }
        public int limitepcthoras_3 { get; set; }
        public int limitepcthoras_4 { get; set; }
        public int limitepcthoras_5 { get; set; }
        public int limitepcthoras_6 { get; set; }
        public string limiteqtdhoras_1 { get; set; }
        public string limiteqtdhoras_2 { get; set; }
        public string limiteqtdhoras_3 { get; set; }
        public string limiteqtdhoras_4 { get; set; }
        public string limiteqtdhoras_5 { get; set; }
        public string limiteqtdhoras_6 { get; set; }
        public int tipoacumulo { get; set; }
        public string limitehorasDiarios_1 { get; set; }
        public string limitehorasDiarios_2 { get; set; }
        public string limitehorasDiarios_3 { get; set; }
        public string limitehorasDiarios_4 { get; set; }
        public string limitehorasDiarios_5 { get; set; }
        public string limitehorasDiarios_6 { get; set; }
        public string limitehorasDiarios_7 { get; set; }
        public string limitehorasDiarios_8 { get; set; }
        public string limitehorasDiarios_9 { get; set; }
        public bool bancoHorasPorPercentual { get; set; }
        public string LimiteAlertaCredito { get; set; }
        public string LimiteAlertaDebito { get; set; }
        public Nullable<bool> FechamentoPercentualHE { get; set; }
        public string FechamentoPercentualHELimite1 { get; set; }
        public string FechamentoPercentualHELimite2 { get; set; }
        public string FechamentoPercentualHEPercentual1 { get; set; }
        public string FechamentoPercentualHEPercentual2 { get; set; }
        public Nullable<bool> bancoHorasDiarioMensal { get; set; }
        public string limiteHorasBancoHorasDiarioMensal { get; set; }
        public string limitehorasDiarioMensal_1 { get; set; }
        public string limitehorasDiarioMensal_2 { get; set; }
        public string limitehorasDiarioMensal_3 { get; set; }
        public string limitehorasDiarioMensal_4 { get; set; }
        public string limitehorasDiarioMensal_5 { get; set; }
        public string limitehorasDiarioMensal_6 { get; set; }
        public string limitehorasDiarioMensal_7 { get; set; }
        public string limitehorasDiarioMensal_8 { get; set; }
        public string limitehorasDiarioMensal_9 { get; set; }
        public string SaldoBh_1 { get; set; }
        public string SaldoBh_2 { get; set; }
        public string SaldoBh_3 { get; set; }
        public string SaldoBh_4 { get; set; }
        public string SaldoBh_5 { get; set; }
        public string SaldoBh_6 { get; set; }
        public string SaldoBh_7 { get; set; }
        public string SaldoBh_8 { get; set; }
        public string SaldoBh_9 { get; set; }
        public string LimiteBancoHorasSemanal { get; set; }
        public System.DateTime ctl_inicio { get; set; }
        public System.DateTime ctl_fim { get; set; }
    }
}
