//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistradorPontoWeb.Models.Ponto
{
    using System;
    using System.Collections.Generic;
    
    public partial class bilhetesimp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bilhetesimp()
        {
            this.LocalizacaoRegistroPonto = new HashSet<LocalizacaoRegistroPonto>();
            this.BilhetesImpEnvioAviso = new HashSet<BilhetesImpEnvioAviso>();
        }
    
        public int id { get; set; }
        public string ordem { get; set; }
        public System.DateTime data { get; set; }
        public string hora { get; set; }
        public string func { get; set; }
        public string relogio { get; set; }
        public Nullable<short> importado { get; set; }
        public Nullable<System.DateTime> mar_data { get; set; }
        public string mar_hora { get; set; }
        public string mar_relogio { get; set; }
        public Nullable<short> posicao { get; set; }
        public string ent_sai { get; set; }
        public Nullable<System.DateTime> incdata { get; set; }
        public Nullable<System.DateTime> inchora { get; set; }
        public string incusuario { get; set; }
        public Nullable<System.DateTime> altdata { get; set; }
        public Nullable<System.DateTime> althora { get; set; }
        public string altusuario { get; set; }
        public Nullable<int> codigo { get; set; }
        public string chave { get; set; }
        public string dscodigo { get; set; }
        public string ocorrencia { get; set; }
        public string motivo { get; set; }
        public Nullable<int> idjustificativa { get; set; }
        public Nullable<int> nsr { get; set; }
        public Nullable<int> idLancamentoLoteFuncionario { get; set; }
        public Nullable<int> IdFuncionario { get; set; }
        public string PIS { get; set; }
        public Nullable<System.DateTime> Mar_DataHora { get; set; }
        public Nullable<int> IdRegistroPonto { get; set; }
    
        public virtual LancamentoLoteFuncionario LancamentoLoteFuncionario { get; set; }
        public virtual RegistroPonto RegistroPonto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocalizacaoRegistroPonto> LocalizacaoRegistroPonto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BilhetesImpEnvioAviso> BilhetesImpEnvioAviso { get; set; }
    }
}
