//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistradorPontoWeb.Models.Ponto
{
    using System;
    using System.Collections.Generic;
    
    public partial class contrato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public contrato()
        {
            this.afastamento = new HashSet<afastamento>();
            this.contratofuncionario = new HashSet<contratofuncionario>();
            this.contratousuario = new HashSet<contratousuario>();
        }
    
        public int id { get; set; }
        public int codigo { get; set; }
        public int idempresa { get; set; }
        public string codigocontrato { get; set; }
        public string descricaocontrato { get; set; }
        public System.DateTime incdata { get; set; }
        public System.DateTime inchora { get; set; }
        public string incusuario { get; set; }
        public Nullable<System.DateTime> altdata { get; set; }
        public Nullable<System.DateTime> althora { get; set; }
        public string altusuario { get; set; }
        public Nullable<int> idIntegracao { get; set; }
        public Nullable<short> DiaFechamentoInicial { get; set; }
        public Nullable<short> DiaFechamentoFinal { get; set; }
        public Nullable<int> IdHorarioPadraoFunc { get; set; }
        public Nullable<int> TipoHorarioPadraoFunc { get; set; }
        public System.DateTime ctl_inicio { get; set; }
        public System.DateTime ctl_fim { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<afastamento> afastamento { get; set; }
        public virtual empresa empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contratofuncionario> contratofuncionario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contratousuario> contratousuario { get; set; }
    }
}
