//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistradorPontoWeb.Models.Ponto
{
    using System;
    using System.Collections.Generic;
    
    public partial class cw_acesso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cw_acesso()
        {
            this.cw_acessocampo = new HashSet<cw_acessocampo>();
            this.cw_grupoacesso = new HashSet<cw_grupoacesso>();
        }
    
        public int id { get; set; }
        public Nullable<int> codigo { get; set; }
        public Nullable<int> idgrupo { get; set; }
        public string formulario { get; set; }
        public Nullable<int> acesso { get; set; }
        public Nullable<System.DateTime> incdata { get; set; }
        public Nullable<System.DateTime> inchora { get; set; }
        public string incusuario { get; set; }
        public Nullable<System.DateTime> altdata { get; set; }
        public Nullable<System.DateTime> althora { get; set; }
        public string altusuario { get; set; }
        public string Controller { get; set; }
        public string Nome { get; set; }
        public string Menu { get; set; }
        public Nullable<short> Consultar { get; set; }
        public Nullable<short> Excluir { get; set; }
        public Nullable<short> Cadastrar { get; set; }
        public Nullable<short> Alterar { get; set; }
    
        public virtual cw_grupo cw_grupo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cw_acessocampo> cw_acessocampo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cw_grupoacesso> cw_grupoacesso { get; set; }
    }
}
