//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistradorPontoWeb.Models.Ponto
{
    using System;
    using System.Collections.Generic;
    
    public partial class cw_grupoacesso
    {
        public int ID { get; set; }
        public int codigo { get; set; }
        public int IDCw_Grupo { get; set; }
        public int IDCw_Acesso { get; set; }
        public Nullable<short> Consultar { get; set; }
        public Nullable<short> Excluir { get; set; }
        public Nullable<short> Cadastrar { get; set; }
        public Nullable<short> Alterar { get; set; }
        public Nullable<System.DateTime> incdata { get; set; }
        public Nullable<System.DateTime> inchora { get; set; }
        public string incusuario { get; set; }
        public Nullable<System.DateTime> altdata { get; set; }
        public Nullable<System.DateTime> althora { get; set; }
        public string altusuario { get; set; }
        public System.DateTime ctl_inicio { get; set; }
        public System.DateTime ctl_fim { get; set; }
    
        public virtual cw_acesso cw_acesso { get; set; }
        public virtual cw_grupo cw_grupo { get; set; }
    }
}
