//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistradorPontoWeb.Models.Ponto
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorarioInItinere
    {
        public int id { get; set; }
        public Nullable<int> idhorario { get; set; }
        public int codigo { get; set; }
        public Nullable<int> Dia { get; set; }
        public bool MarcaDiaBool { get; set; }
        public decimal PercentualDentroJornada { get; set; }
        public decimal PercentualDentroFora { get; set; }
        public Nullable<System.DateTime> incdata { get; set; }
        public Nullable<System.DateTime> inchora { get; set; }
        public string incusuario { get; set; }
        public Nullable<System.DateTime> altdata { get; set; }
        public Nullable<System.DateTime> althora { get; set; }
        public string altusuario { get; set; }
    
        public virtual horario horario { get; set; }
    }
}
