//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistradorPontoWeb.Models.Ponto
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorarioDinamicoLimiteDdsr
    {
        public int Id { get; set; }
        public int Codigo { get; set; }
        public string LimitePerdaDsr { get; set; }
        public string QtdHorasDsr { get; set; }
        public int IdHorarioDinamico { get; set; }
        public System.DateTime IncData { get; set; }
        public System.DateTime IncHora { get; set; }
        public string IncUsuario { get; set; }
        public Nullable<System.DateTime> AltData { get; set; }
        public Nullable<System.DateTime> AltHora { get; set; }
        public string AltUsuario { get; set; }
        public System.DateTime ctl_inicio { get; set; }
        public System.DateTime ctl_fim { get; set; }
    
        public virtual HorarioDinamico HorarioDinamico { get; set; }
    }
}
