//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistradorPontoWeb.Models.Ponto
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroPontoTentativa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RegistroPontoTentativa()
        {
            this.IdentificacaoReconhecimentoFacil = new HashSet<IdentificacaoReconhecimentoFacil>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Codigo { get; set; }
        public Nullable<System.DateTime> IncData { get; set; }
        public Nullable<System.DateTime> IncHora { get; set; }
        public string IncUsuario { get; set; }
        public Nullable<System.DateTime> AltData { get; set; }
        public Nullable<System.DateTime> AltHora { get; set; }
        public string altusuario { get; set; }
        public Nullable<System.DateTime> Batida { get; set; }
        public string OrigemRegistro { get; set; }
        public string usuario { get; set; }
        public string IpPublico { get; set; }
        public string IpInterno { get; set; }
        public string XFORWARDEDFOR { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public string Browser { get; set; }
        public string BrowserVersao { get; set; }
        public string BrowserPlatform { get; set; }
        public string TimeZone { get; set; }
        public string Erro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdentificacaoReconhecimentoFacil> IdentificacaoReconhecimentoFacil { get; set; }
    }
}
