//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistradorPontoWeb.Models.Ponto
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_Configuracao_CDC_Tabela
    {
        public int Idf_Configuracao_CDC_Tabela { get; set; }
        public string Nme_Schema { get; set; }
        public string Nme_Tabela { get; set; }
        public int Idf_Tipo_Configuracao_CDC_Tabela { get; set; }
        public System.DateTime Dta_Cadastro { get; set; }
    
        public virtual TAB_Tipo_Configuracao_CDC_Tabela TAB_Tipo_Configuracao_CDC_Tabela { get; set; }
    }
}
