//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistradorPontoWeb.Models.Ponto
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferenciaBilhetes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransferenciaBilhetes()
        {
            this.TransferenciaBilhetesDetalhes = new HashSet<TransferenciaBilhetesDetalhes>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Codigo { get; set; }
        public Nullable<System.DateTime> Incdata { get; set; }
        public Nullable<System.DateTime> Inchora { get; set; }
        public string Incusuario { get; set; }
        public Nullable<System.DateTime> Altdata { get; set; }
        public Nullable<System.DateTime> Althora { get; set; }
        public string Altusuario { get; set; }
        public Nullable<System.DateTime> DataInicio { get; set; }
        public Nullable<System.DateTime> DataFim { get; set; }
        public Nullable<int> IdFuncionarioOrigem { get; set; }
        public Nullable<int> IdFuncionarioDestino { get; set; }
    
        public virtual funcionario funcionario { get; set; }
        public virtual funcionario funcionario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferenciaBilhetesDetalhes> TransferenciaBilhetesDetalhes { get; set; }
    }
}
