//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cwkPontoMT.Integracao.Relogios.Dimep
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENDAMENTOS
    {
        public AGENDAMENTOS()
        {
            this.RELOGIOS = new HashSet<RELOGIOS>();
        }
    
        public int IDAGENDAMENTO { get; set; }
        public string DESCRICAO { get; set; }
        public Nullable<int> INTERVALOEXECUCAODIA { get; set; }
        public Nullable<int> INTERVALOEXECUCAOHORA { get; set; }
        public Nullable<int> INTERVALOEXECUCAOMINUTO { get; set; }
        public Nullable<System.DateTime> HORARIOEXECUCAODATA { get; set; }
        public Nullable<System.DateTime> HORARIOEXECUCAOHORA { get; set; }
        public Nullable<bool> NUMEROEXECUCAOINFINITAMENTE { get; set; }
        public Nullable<bool> NUMEROEXECUCAOVALORDETERMINADO { get; set; }
        public Nullable<int> NUMEROEXECUCAOVALOR { get; set; }
        public Nullable<System.DateTime> HORARIOOPERACAOINICIO { get; set; }
        public Nullable<System.DateTime> HORARIOOPERACAOFIM { get; set; }
        public Nullable<bool> ENVIACOLETA { get; set; }
        public Nullable<bool> ENVIADATAHORA { get; set; }
        public Nullable<bool> ENVIACONFIGURACAO { get; set; }
        public Nullable<bool> ENVIAPEDESTATUS { get; set; }
        public Nullable<bool> ENVIASINCRONIZACAO { get; set; }
        public Nullable<bool> ENVIAHORARIOVERAO { get; set; }
        public Nullable<int> IDSERVICO { get; set; }
    
        public virtual SERVICOS SERVICOS { get; set; }
        public virtual ICollection<RELOGIOS> RELOGIOS { get; set; }
    }
}
