//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cwkPontoMT.Integracao.Relogios.Dimep
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIGURACOESBANCODEDADOS
    {
        public CONFIGURACOESBANCODEDADOS()
        {
            this.LAYOUTBANCODEDADOS = new HashSet<LAYOUTBANCODEDADOS>();
            this.RELOGIOS = new HashSet<RELOGIOS>();
        }
    
        public int IDCONFIGURACAOBANCODEDADOS { get; set; }
        public Nullable<int> TIPOEXPORTACAO { get; set; }
        public Nullable<int> TIPOBANCO { get; set; }
        public string CAMINHOBANCO { get; set; }
        public string SERVIDOR { get; set; }
        public string USUARIO { get; set; }
        public string SENHA { get; set; }
        public string BANCO { get; set; }
        public string ESQUEMA { get; set; }
        public string TABELA { get; set; }
        public Nullable<bool> WINDOWSAUTH { get; set; }
        public Nullable<bool> SQLSERVER { get; set; }
    
        public virtual ICollection<LAYOUTBANCODEDADOS> LAYOUTBANCODEDADOS { get; set; }
        public virtual ICollection<RELOGIOS> RELOGIOS { get; set; }
    }
}
