//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cwkPontoMT.Integracao.Relogios.Dimep
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIGURACOESNBIO
    {
        public int IDCONFIGURACAONBIO { get; set; }
        public int IDCONFIGURACAO { get; set; }
        public Nullable<int> QTDMINIMADIGITOSCARTAO { get; set; }
        public Nullable<int> QTDMAXIMADIGITOSCARTAO { get; set; }
        public Nullable<bool> FERIADO { get; set; }
        public Nullable<bool> SINALEIRO { get; set; }
        public Nullable<bool> JORNADA { get; set; }
        public Nullable<bool> VIA { get; set; }
        public Nullable<bool> MENSAGEM { get; set; }
        public Nullable<int> IDMENSAGEMUSUARIOGRUPO { get; set; }
        public Nullable<int> IDMENSAGEMFUNCAOGRUPO { get; set; }
        public Nullable<int> IDMENSAGEMSISTEMAGRUPO { get; set; }
        public Nullable<int> IDFERIADOGRUPO { get; set; }
        public Nullable<int> IDSINALEIROGRUPO { get; set; }
        public Nullable<int> IDGRUPOJORNADA { get; set; }
        public Nullable<int> CONTADORESACESSO { get; set; }
        public Nullable<bool> REGISTRABLOQUEADO { get; set; }
        public Nullable<bool> CHECAGEM { get; set; }
        public Nullable<bool> SENHA { get; set; }
        public Nullable<int> TABCARTOES { get; set; }
        public Nullable<int> TABCODIGOSALTERNATIVOS { get; set; }
        public Nullable<int> TABJORNADASSEMANAIS { get; set; }
        public Nullable<int> TABJORNADASMENSAIS { get; set; }
        public Nullable<int> TABJORNADASPERIODICAS { get; set; }
        public Nullable<int> TABTURNOS { get; set; }
        public Nullable<int> TABSINALEIROS { get; set; }
        public Nullable<int> TABFERIADOS { get; set; }
        public Nullable<int> TABFUNCOES { get; set; }
        public Nullable<int> TABMENSAGEMUSUARIOS { get; set; }
        public string FORMATOCARTAO { get; set; }
        public Nullable<bool> UTILIZACRIPTOGRAFIA { get; set; }
        public Nullable<bool> CRIPTOGRAFIA8DIGITOS { get; set; }
        public Nullable<bool> CRIPTOGRAFIA12DIGITOS { get; set; }
        public string VETOR1 { get; set; }
        public string VERIFICADOR1 { get; set; }
        public string VETOR2 { get; set; }
        public string VERIFICADOR2 { get; set; }
    
        public virtual CONFIGURACOES CONFIGURACOES { get; set; }
        public virtual FERIADOGRUPO FERIADOGRUPO { get; set; }
        public virtual GRUPOJORNADA GRUPOJORNADA { get; set; }
        public virtual MENSAGEMFUNCAOGRUPO MENSAGEMFUNCAOGRUPO { get; set; }
        public virtual MENSAGEMSISTEMAGRUPO MENSAGEMSISTEMAGRUPO { get; set; }
        public virtual MENSAGEMUSUARIOGRUPO MENSAGEMUSUARIOGRUPO { get; set; }
        public virtual SINALEIROGRUPO SINALEIROGRUPO { get; set; }
    }
}
