//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cwkPontoMT.Integracao.Relogios.Dimep
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIGURACOESMPIP
    {
        public int IDCONFIGURACAOMICROPOINTIP { get; set; }
        public int IDCONFIGURACAO { get; set; }
        public Nullable<short> QTDDIGITOSCARTAO { get; set; }
        public Nullable<byte> LEITURACARTAOCOMCHECAGEM { get; set; }
        public Nullable<byte> VERIFICAVERSAOCARTAO { get; set; }
        public Nullable<short> CODIGOPERSONALIZACAO { get; set; }
    
        public virtual CONFIGURACOES CONFIGURACOES { get; set; }
    }
}
