//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cwkPontoMT.Integracao.Relogios.Dimep
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIGURACOESSERVICOS
    {
        public CONFIGURACOESSERVICOS()
        {
            this.SERVICOS = new HashSet<SERVICOS>();
        }
    
        public int IDCONFIGURACAOSERVICO { get; set; }
        public string DESCRICAO { get; set; }
        public string DIRETORIOENTRADA { get; set; }
        public string DIRETORIOSAIDA { get; set; }
        public string LOG { get; set; }
        public Nullable<int> FUSOHORARIO { get; set; }
        public Nullable<bool> RELOGIOENTRAHORARIOVERAO { get; set; }
        public Nullable<System.DateTime> INICIOHORARIODEVERAO { get; set; }
        public Nullable<System.DateTime> FIMHORARIODEVERAO { get; set; }
        public Nullable<bool> UMARQMOVTOTODOSRELOGIOS { get; set; }
        public string NOMEARQMOVTOTODOSRELOGIOS { get; set; }
        public Nullable<bool> CRIARAPENASUMARQUIVODIARIO { get; set; }
        public Nullable<bool> INTEGRACAOTRK2 { get; set; }
        public Nullable<bool> RENOMARQCOLETADIATDSRELOGIOS { get; set; }
        public Nullable<bool> COLETARSOMENTEREGISTROSPONTO { get; set; }
        public Nullable<bool> ENVIARPARABANCOEXTERNO { get; set; }
        public Nullable<System.DateTime> HORARENOMEARARQUIVO { get; set; }
        public Nullable<bool> MONITORACOMANDOSVIABANCO { get; set; }
        public Nullable<bool> SERVICOREP { get; set; }
    
        public virtual ICollection<SERVICOS> SERVICOS { get; set; }
    }
}
