//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cwkPontoMT.Integracao.Relogios.Dimep
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIGURACOES
    {
        public CONFIGURACOES()
        {
            this.CONFIGURACOESMPIP = new HashSet<CONFIGURACOESMPIP>();
            this.CONFIGURACOESMINIREP = new HashSet<CONFIGURACOESMINIREP>();
            this.RELOGIOS = new HashSet<RELOGIOS>();
            this.CONFIGURACOESREP = new HashSet<CONFIGURACOESREP>();
        }
    
        public int IDCONFIGURACAO { get; set; }
        public string DESCRICAO { get; set; }
        public Nullable<int> TIPO { get; set; }
    
        public virtual CONFIGURACOESBIO CONFIGURACOESBIO { get; set; }
        public virtual ICollection<CONFIGURACOESMPIP> CONFIGURACOESMPIP { get; set; }
        public virtual CONFIGURACOESLITE CONFIGURACOESLITE { get; set; }
        public virtual ICollection<CONFIGURACOESMINIREP> CONFIGURACOESMINIREP { get; set; }
        public virtual CONFIGURACOESNBIO CONFIGURACOESNBIO { get; set; }
        public virtual ICollection<RELOGIOS> RELOGIOS { get; set; }
        public virtual ICollection<CONFIGURACOESREP> CONFIGURACOESREP { get; set; }
    }
}
