//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cwkPontoMT.Integracao.Relogios.Dimep
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRUPOJORNADADETALHE
    {
        public int IDGRUPOJORNADADETALHE { get; set; }
        public int IDGRUPOJORNADA { get; set; }
        public int IDJORNADA { get; set; }
        public Nullable<short> SEQUENCIA { get; set; }
    
        public virtual GRUPOJORNADA GRUPOJORNADA { get; set; }
        public virtual JORNADA JORNADA { get; set; }
    }
}
