//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cwkPontoMT.Integracao.Relogios.Dimep
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORICOSTATUSRELOGIO
    {
        public int IDHISTORICOSTATUSRELOGIO { get; set; }
        public int IDRELOGIO { get; set; }
        public byte ESTADOBOBINA { get; set; }
        public byte ESTADOMRP { get; set; }
        public byte ESTADORELOGIO { get; set; }
        public bool POSSUIMARCACOES { get; set; }
        public bool POSSUINOVOSTEMPLATES { get; set; }
        public System.DateTime DATAHORASTATUS { get; set; }
        public bool GERANDOAFD { get; set; }
        public bool GERANDORIM { get; set; }
    
        public virtual RELOGIOS RELOGIOS { get; set; }
    }
}
