//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cwkPontoMT.Integracao.Relogios.Dimep
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTSINCTEMPLATESERVER
    {
        public int IDHISTSINCTEMPLATESERVER { get; set; }
        public Nullable<System.DateTime> DATAHORAPENDENCIASINCRONIZACAO { get; set; }
        public Nullable<System.DateTime> DATAHORASINCRONIZACAO { get; set; }
        public Nullable<int> IDPESSOA { get; set; }
        public Nullable<bool> SUCESSO { get; set; }
    
        public virtual PESSOA PESSOA { get; set; }
    }
}
