//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cwkPontoMT.Integracao.Relogios.Dimep
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTEGRACAONOTIFICADORBD
    {
        public int IDINTEGRACAONOTIFICADORBD { get; set; }
        public int TIPOBANCO { get; set; }
        public string SERVIDOR { get; set; }
        public string BANCODADOS { get; set; }
        public string USUARIO { get; set; }
        public string SENHA { get; set; }
        public Nullable<bool> WINDOWSAUTH { get; set; }
        public Nullable<bool> SQLSERVER { get; set; }
    }
}
