//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cwkPontoMT.Integracao.Relogios.Dimep
{
    using System;
    using System.Collections.Generic;
    
    public partial class LAYOUTBANCODEDADOS
    {
        public int IDLAYOUTBANCODEDADOS { get; set; }
        public Nullable<int> DADOS { get; set; }
        public Nullable<int> TIPOCAMPO { get; set; }
        public string CAMPODESTINO { get; set; }
        public string SEQUENCE { get; set; }
        public Nullable<int> TIPOCAMPODESTINO { get; set; }
        public string MASCARA { get; set; }
        public string CAMPOFIXO { get; set; }
        public string NAOGRAVAR { get; set; }
        public string FORMATO { get; set; }
        public Nullable<int> IDCONFIGURACAOBANCODEDADOS { get; set; }
    
        public virtual CONFIGURACOESBANCODEDADOS CONFIGURACOESBANCODEDADOS { get; set; }
    }
}
