//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cwkPontoMT.Integracao.Relogios.Dimep
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENSAGEMFUNCAO
    {
        public int IDMENSAGEMFUNCAO { get; set; }
        public byte CODIGOMENSAGEMFUNCAO { get; set; }
        public string DESCRICAO { get; set; }
        public string MENSAGEM { get; set; }
        public bool ATIVADA { get; set; }
        public bool CONSULTALISTA { get; set; }
        public bool COMACIONAMENTO { get; set; }
        public bool CONSULTAJORNADA { get; set; }
        public bool PEDESUPERVISOR { get; set; }
        public bool ACEITATECLADO { get; set; }
        public bool ARMAZENABLOQUEADO { get; set; }
        public bool ARMAZENAPEMITIDO { get; set; }
        public int IDMENSAGEMFUNCAOGRUPO { get; set; }
    
        public virtual MENSAGEMFUNCAOGRUPO MENSAGEMFUNCAOGRUPO { get; set; }
    }
}
