//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cwkPontoMT.Integracao.Relogios.Dimep
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERMISSOES
    {
        public PERMISSOES()
        {
            this.USUARIOS = new HashSet<USUARIOS>();
        }
    
        public int IDPERMISSAO { get; set; }
        public Nullable<int> ORDEM { get; set; }
        public Nullable<int> PAI { get; set; }
    
        public virtual ICollection<USUARIOS> USUARIOS { get; set; }
    }
}
