//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cwkPontoMT.Integracao.Relogios.Dimep
{
    using System;
    using System.Collections.Generic;
    
    public partial class RELOGIOS
    {
        public RELOGIOS()
        {
            this.COLETA = new HashSet<COLETA>();
            this.EXECUCAOCOMANDO = new HashSet<EXECUCAOCOMANDO>();
            this.HISTEXECUCAOCOMANDO = new HashSet<HISTEXECUCAOCOMANDO>();
            this.HISTORICOSTATUSRELOGIO = new HashSet<HISTORICOSTATUSRELOGIO>();
            this.HISTSINCRONIZACAOCARTAO = new HashSet<HISTSINCRONIZACAOCARTAO>();
            this.HISTSINCRONIZACAOCENTROCUSTO = new HashSet<HISTSINCRONIZACAOCENTROCUSTO>();
            this.HISTSINCRONIZACAOCONFIGURACAO = new HashSet<HISTSINCRONIZACAOCONFIGURACAO>();
            this.HISTSINCRONIZACAOPESSOA = new HashSet<HISTSINCRONIZACAOPESSOA>();
            this.HISTSINCRONIZACAOSUPERVISOR = new HashSet<HISTSINCRONIZACAOSUPERVISOR>();
            this.HISTSINCRONIZACAOTEMPLATE = new HashSet<HISTSINCRONIZACAOTEMPLATE>();
            this.LOG = new HashSet<LOG>();
            this.RELOGIOJORNADA = new HashSet<RELOGIOJORNADA>();
            this.RELOGIOMENSAGEM = new HashSet<RELOGIOMENSAGEM>();
            this.SINCRONIZACAOCARTAO = new HashSet<SINCRONIZACAOCARTAO>();
            this.SINCRONIZACAOCENTROCUSTO = new HashSet<SINCRONIZACAOCENTROCUSTO>();
            this.SINCRONIZACAOCONFIGURACAO = new HashSet<SINCRONIZACAOCONFIGURACAO>();
            this.SINCRONIZACAOPESSOA = new HashSet<SINCRONIZACAOPESSOA>();
            this.SINCRONIZACAOSUPERVISOR = new HashSet<SINCRONIZACAOSUPERVISOR>();
            this.SINCRONIZACAOTEMPLATE = new HashSet<SINCRONIZACAOTEMPLATE>();
            this.STATUSCOMPLETO = new HashSet<STATUSCOMPLETO>();
            this.STATUSRELOGIO = new HashSet<STATUSRELOGIO>();
            this.AGENDAMENTOS = new HashSet<AGENDAMENTOS>();
            this.CONFIGURACOESBANCODEDADOS = new HashSet<CONFIGURACOESBANCODEDADOS>();
            this.PESSOA = new HashSet<PESSOA>();
            this.SUPERVISOR = new HashSet<SUPERVISOR>();
            this.TECNOLOGIALEITURA = new HashSet<TECNOLOGIALEITURA>();
        }
    
        public int IDRELOGIO { get; set; }
        public string DESCRICAO { get; set; }
        public string VERSAO { get; set; }
        public string ENDERECO { get; set; }
        public string ENDERECOALTERNATIVO { get; set; }
        public int PORTA { get; set; }
        public Nullable<int> PORTAENDERECOALTERNATIVO { get; set; }
        public Nullable<int> NUMERORELOGIO { get; set; }
        public Nullable<long> NUMEROFABRICACAO { get; set; }
        public Nullable<int> FUSOHORARIO { get; set; }
        public Nullable<bool> RELOGIOENTRAHORARIODEVERAO { get; set; }
        public Nullable<System.DateTime> INICIOHORARIODEVERAO { get; set; }
        public Nullable<System.DateTime> FIMHORARIODEVERAO { get; set; }
        public Nullable<bool> ATIVO { get; set; }
        public Nullable<bool> EXCLUIDO { get; set; }
        public Nullable<int> IDSERVICO { get; set; }
        public Nullable<int> IDCONFIGURACAO { get; set; }
        public Nullable<int> IDEMPRESA { get; set; }
        public Nullable<int> IDULTIMACOLETAAFD { get; set; }
        public Nullable<bool> PENDRIVE { get; set; }
        public string LOCALIZACAO { get; set; }
        public string ULTIMONSR { get; set; }
        public Nullable<int> TIPOSENSOR { get; set; }
        public Nullable<int> IDGRUPOJORNADA { get; set; }
        public Nullable<decimal> TEMPOATUACAO { get; set; }
        public Nullable<int> TAXAAMOSTRAGEM { get; set; }
        public Nullable<bool> LEITOR1 { get; set; }
        public Nullable<bool> LEITOR2 { get; set; }
        public Nullable<int> TIPOACIONAMENTO { get; set; }
        public Nullable<bool> ACESSOCONTROLADO { get; set; }
        public Nullable<bool> TERMINALATIVADO { get; set; }
        public Nullable<bool> IMPRESSORA { get; set; }
        public Nullable<bool> SINCRONIZAR { get; set; }
        public Nullable<bool> GSM { get; set; }
        public Nullable<byte> QUANTIDADELEITORES { get; set; }
        public Nullable<byte> SENTIDOREGISTRO { get; set; }
        public string CPF { get; set; }
        public string CHAVERSA { get; set; }
        public string EXPOENTE { get; set; }
        public Nullable<bool> GRAVARLOGMONITORACAO { get; set; }
    
        public virtual ICollection<COLETA> COLETA { get; set; }
        public virtual CONFIGURACOES CONFIGURACOES { get; set; }
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual ICollection<EXECUCAOCOMANDO> EXECUCAOCOMANDO { get; set; }
        public virtual GRUPOJORNADA GRUPOJORNADA { get; set; }
        public virtual ICollection<HISTEXECUCAOCOMANDO> HISTEXECUCAOCOMANDO { get; set; }
        public virtual ICollection<HISTORICOSTATUSRELOGIO> HISTORICOSTATUSRELOGIO { get; set; }
        public virtual ICollection<HISTSINCRONIZACAOCARTAO> HISTSINCRONIZACAOCARTAO { get; set; }
        public virtual ICollection<HISTSINCRONIZACAOCENTROCUSTO> HISTSINCRONIZACAOCENTROCUSTO { get; set; }
        public virtual ICollection<HISTSINCRONIZACAOCONFIGURACAO> HISTSINCRONIZACAOCONFIGURACAO { get; set; }
        public virtual ICollection<HISTSINCRONIZACAOPESSOA> HISTSINCRONIZACAOPESSOA { get; set; }
        public virtual ICollection<HISTSINCRONIZACAOSUPERVISOR> HISTSINCRONIZACAOSUPERVISOR { get; set; }
        public virtual ICollection<HISTSINCRONIZACAOTEMPLATE> HISTSINCRONIZACAOTEMPLATE { get; set; }
        public virtual ICollection<LOG> LOG { get; set; }
        public virtual ICollection<RELOGIOJORNADA> RELOGIOJORNADA { get; set; }
        public virtual ICollection<RELOGIOMENSAGEM> RELOGIOMENSAGEM { get; set; }
        public virtual SERVICOS SERVICOS { get; set; }
        public virtual ICollection<SINCRONIZACAOCARTAO> SINCRONIZACAOCARTAO { get; set; }
        public virtual ICollection<SINCRONIZACAOCENTROCUSTO> SINCRONIZACAOCENTROCUSTO { get; set; }
        public virtual ICollection<SINCRONIZACAOCONFIGURACAO> SINCRONIZACAOCONFIGURACAO { get; set; }
        public virtual ICollection<SINCRONIZACAOPESSOA> SINCRONIZACAOPESSOA { get; set; }
        public virtual ICollection<SINCRONIZACAOSUPERVISOR> SINCRONIZACAOSUPERVISOR { get; set; }
        public virtual ICollection<SINCRONIZACAOTEMPLATE> SINCRONIZACAOTEMPLATE { get; set; }
        public virtual ICollection<STATUSCOMPLETO> STATUSCOMPLETO { get; set; }
        public virtual ICollection<STATUSRELOGIO> STATUSRELOGIO { get; set; }
        public virtual ICollection<AGENDAMENTOS> AGENDAMENTOS { get; set; }
        public virtual ICollection<CONFIGURACOESBANCODEDADOS> CONFIGURACOESBANCODEDADOS { get; set; }
        public virtual ICollection<PESSOA> PESSOA { get; set; }
        public virtual ICollection<SUPERVISOR> SUPERVISOR { get; set; }
        public virtual ICollection<TECNOLOGIALEITURA> TECNOLOGIALEITURA { get; set; }
    }
}
