//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cwkPontoMT.Integracao.Relogios.Dimep
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICOS
    {
        public SERVICOS()
        {
            this.AGENDAMENTOS = new HashSet<AGENDAMENTOS>();
            this.LOG = new HashSet<LOG>();
            this.RELOGIOS = new HashSet<RELOGIOS>();
        }
    
        public int IDSERVICO { get; set; }
        public string DESCRICAO { get; set; }
        public Nullable<int> IDCONFIGURACAOSERVICOS { get; set; }
        public string ENDERECO { get; set; }
        public Nullable<int> PORTA { get; set; }
        public string ENDERECOGSM { get; set; }
        public Nullable<int> PORTAGSM { get; set; }
        public Nullable<bool> GSM { get; set; }
        public string ENDERECOSERVIDOR { get; set; }
    
        public virtual ICollection<AGENDAMENTOS> AGENDAMENTOS { get; set; }
        public virtual CONFIGURACOESSERVICOS CONFIGURACOESSERVICOS { get; set; }
        public virtual ICollection<LOG> LOG { get; set; }
        public virtual ICollection<RELOGIOS> RELOGIOS { get; set; }
    }
}
