//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cwkPontoMT.Integracao.Relogios.Dimep
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SERVCOM_NETEntities : DbContext
    {
        public SERVCOM_NETEntities()
            : base("name=SERVCOM_NETEntities")
        {
        }

        public SERVCOM_NETEntities(string conexao)
            : base(conexao)
        {
            Database.Connection.Open();
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AGENDAMENTOS> AGENDAMENTOS { get; set; }
        public virtual DbSet<ASSOCIARLOTETEMP> ASSOCIARLOTETEMP { get; set; }
        public virtual DbSet<CARTAO> CARTAO { get; set; }
        public virtual DbSet<CENTROCUSTO> CENTROCUSTO { get; set; }
        public virtual DbSet<COLETA> COLETA { get; set; }
        public virtual DbSet<CONFIGURACOES> CONFIGURACOES { get; set; }
        public virtual DbSet<CONFIGURACOESBANCODEDADOS> CONFIGURACOESBANCODEDADOS { get; set; }
        public virtual DbSet<CONFIGURACOESBIO> CONFIGURACOESBIO { get; set; }
        public virtual DbSet<CONFIGURACOESLITE> CONFIGURACOESLITE { get; set; }
        public virtual DbSet<CONFIGURACOESMINIREP> CONFIGURACOESMINIREP { get; set; }
        public virtual DbSet<CONFIGURACOESMPIP> CONFIGURACOESMPIP { get; set; }
        public virtual DbSet<CONFIGURACOESNBIO> CONFIGURACOESNBIO { get; set; }
        public virtual DbSet<CONFIGURACOESREP> CONFIGURACOESREP { get; set; }
        public virtual DbSet<CONFIGURACOESSERVICOS> CONFIGURACOESSERVICOS { get; set; }
        public virtual DbSet<CONTROLECUSTOMIZACAO> CONTROLECUSTOMIZACAO { get; set; }
        public virtual DbSet<EMPRESA> EMPRESA { get; set; }
        public virtual DbSet<EXECUCAOCOMANDO> EXECUCAOCOMANDO { get; set; }
        public virtual DbSet<EXECUCAOPARCIALGSM> EXECUCAOPARCIALGSM { get; set; }
        public virtual DbSet<FERIADO> FERIADO { get; set; }
        public virtual DbSet<FERIADOGRUPO> FERIADOGRUPO { get; set; }
        public virtual DbSet<FORMATOEXPORTACAO> FORMATOEXPORTACAO { get; set; }
        public virtual DbSet<FORMATOEXPORTACAOPENDRIVE> FORMATOEXPORTACAOPENDRIVE { get; set; }
        public virtual DbSet<FORMATONOMEARQUIVO> FORMATONOMEARQUIVO { get; set; }
        public virtual DbSet<GRUPOJORNADA> GRUPOJORNADA { get; set; }
        public virtual DbSet<GRUPOJORNADADETALHE> GRUPOJORNADADETALHE { get; set; }
        public virtual DbSet<HISTEXECUCAOCOMANDO> HISTEXECUCAOCOMANDO { get; set; }
        public virtual DbSet<HISTORICOSTATUSRELOGIO> HISTORICOSTATUSRELOGIO { get; set; }
        public virtual DbSet<HISTSINCRONIZACAOCARTAO> HISTSINCRONIZACAOCARTAO { get; set; }
        public virtual DbSet<HISTSINCRONIZACAOCENTROCUSTO> HISTSINCRONIZACAOCENTROCUSTO { get; set; }
        public virtual DbSet<HISTSINCRONIZACAOCONFIGURACAO> HISTSINCRONIZACAOCONFIGURACAO { get; set; }
        public virtual DbSet<HISTSINCRONIZACAOPESSOA> HISTSINCRONIZACAOPESSOA { get; set; }
        public virtual DbSet<HISTSINCRONIZACAOSUPERVISOR> HISTSINCRONIZACAOSUPERVISOR { get; set; }
        public virtual DbSet<HISTSINCRONIZACAOTEMPLATE> HISTSINCRONIZACAOTEMPLATE { get; set; }
        public virtual DbSet<HISTSINCTEMPLATESERVER> HISTSINCTEMPLATESERVER { get; set; }
        public virtual DbSet<IDIOMAS> IDIOMAS { get; set; }
        public virtual DbSet<INTEGRACAONOTIFICADORBD> INTEGRACAONOTIFICADORBD { get; set; }
        public virtual DbSet<JORNADA> JORNADA { get; set; }
        public virtual DbSet<LAYOUTBANCODEDADOS> LAYOUTBANCODEDADOS { get; set; }
        public virtual DbSet<LOG> LOG { get; set; }
        public virtual DbSet<MASCARAEVENTO> MASCARAEVENTO { get; set; }
        public virtual DbSet<MENSAGEMFUNCAO> MENSAGEMFUNCAO { get; set; }
        public virtual DbSet<MENSAGEMFUNCAOGRUPO> MENSAGEMFUNCAOGRUPO { get; set; }
        public virtual DbSet<MENSAGEMSISTEMA> MENSAGEMSISTEMA { get; set; }
        public virtual DbSet<MENSAGEMSISTEMAGRUPO> MENSAGEMSISTEMAGRUPO { get; set; }
        public virtual DbSet<MENSAGEMUSUARIO> MENSAGEMUSUARIO { get; set; }
        public virtual DbSet<MENSAGEMUSUARIOGRUPO> MENSAGEMUSUARIOGRUPO { get; set; }
        public virtual DbSet<NOMEARQUIVO> NOMEARQUIVO { get; set; }
        public virtual DbSet<PARAMETROS> PARAMETROS { get; set; }
        public virtual DbSet<PERMISSOES> PERMISSOES { get; set; }
        public virtual DbSet<PESSOA> PESSOA { get; set; }
        public virtual DbSet<RELOGIOJORNADA> RELOGIOJORNADA { get; set; }
        public virtual DbSet<RELOGIOMENSAGEM> RELOGIOMENSAGEM { get; set; }
        public virtual DbSet<RELOGIOS> RELOGIOS { get; set; }
        public virtual DbSet<SERVICOS> SERVICOS { get; set; }
        public virtual DbSet<SINALEIRO> SINALEIRO { get; set; }
        public virtual DbSet<SINALEIROGRUPO> SINALEIROGRUPO { get; set; }
        public virtual DbSet<SINCRONIZACAOCARTAO> SINCRONIZACAOCARTAO { get; set; }
        public virtual DbSet<SINCRONIZACAOCENTROCUSTO> SINCRONIZACAOCENTROCUSTO { get; set; }
        public virtual DbSet<SINCRONIZACAOCONFIGURACAO> SINCRONIZACAOCONFIGURACAO { get; set; }
        public virtual DbSet<SINCRONIZACAOPESSOA> SINCRONIZACAOPESSOA { get; set; }
        public virtual DbSet<SINCRONIZACAOSUPERVISOR> SINCRONIZACAOSUPERVISOR { get; set; }
        public virtual DbSet<SINCRONIZACAOTEMPLATE> SINCRONIZACAOTEMPLATE { get; set; }
        public virtual DbSet<SINCRONIZACAOTEMPLATESERVER> SINCRONIZACAOTEMPLATESERVER { get; set; }
        public virtual DbSet<STATUSCOMPLETO> STATUSCOMPLETO { get; set; }
        public virtual DbSet<STATUSRELOGIO> STATUSRELOGIO { get; set; }
        public virtual DbSet<SUPERVISOR> SUPERVISOR { get; set; }
        public virtual DbSet<TABELACENTROCUSTO> TABELACENTROCUSTO { get; set; }
        public virtual DbSet<TABELACREDENCIAIS> TABELACREDENCIAIS { get; set; }
        public virtual DbSet<TABELAFUNCIONARIOS> TABELAFUNCIONARIOS { get; set; }
        public virtual DbSet<TABELALEITURARELOGIO> TABELALEITURARELOGIO { get; set; }
        public virtual DbSet<TABELASUPERVISORES> TABELASUPERVISORES { get; set; }
        public virtual DbSet<TECNOLOGIALEITURA> TECNOLOGIALEITURA { get; set; }
        public virtual DbSet<TEMPLATE> TEMPLATE { get; set; }
        public virtual DbSet<TEMPLATESNOVOS> TEMPLATESNOVOS { get; set; }
        public virtual DbSet<TEMPLATEXDEDO> TEMPLATEXDEDO { get; set; }
        public virtual DbSet<TIPOCOMANDO> TIPOCOMANDO { get; set; }
        public virtual DbSet<TURNO> TURNO { get; set; }
        public virtual DbSet<USUARIOS> USUARIOS { get; set; }
        public virtual DbSet<V20RECORDS> V20RECORDS { get; set; }
        public virtual DbSet<CARTOESEXCLUIDOS> CARTOESEXCLUIDOS { get; set; }
    
        public virtual int SP_DESCRICAOCAMPO(string tABELA, string cOLUNA)
        {
            var tABELAParameter = tABELA != null ?
                new ObjectParameter("TABELA", tABELA) :
                new ObjectParameter("TABELA", typeof(string));
    
            var cOLUNAParameter = cOLUNA != null ?
                new ObjectParameter("COLUNA", cOLUNA) :
                new ObjectParameter("COLUNA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DESCRICAOCAMPO", tABELAParameter, cOLUNAParameter);
        }
    
        public virtual int UP_ALTERAPESSOA(string mATRICULA, string sENHA, string nOME)
        {
            var mATRICULAParameter = mATRICULA != null ?
                new ObjectParameter("MATRICULA", mATRICULA) :
                new ObjectParameter("MATRICULA", typeof(string));
    
            var sENHAParameter = sENHA != null ?
                new ObjectParameter("SENHA", sENHA) :
                new ObjectParameter("SENHA", typeof(string));
    
            var nOMEParameter = nOME != null ?
                new ObjectParameter("NOME", nOME) :
                new ObjectParameter("NOME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_ALTERAPESSOA", mATRICULAParameter, sENHAParameter, nOMEParameter);
        }
    
        public virtual int UP_ALTERAPESSOA_1(string mATRICULA, string sENHA, string nOME, string cENTROCUSTO)
        {
            var mATRICULAParameter = mATRICULA != null ?
                new ObjectParameter("MATRICULA", mATRICULA) :
                new ObjectParameter("MATRICULA", typeof(string));
    
            var sENHAParameter = sENHA != null ?
                new ObjectParameter("SENHA", sENHA) :
                new ObjectParameter("SENHA", typeof(string));
    
            var nOMEParameter = nOME != null ?
                new ObjectParameter("NOME", nOME) :
                new ObjectParameter("NOME", typeof(string));
    
            var cENTROCUSTOParameter = cENTROCUSTO != null ?
                new ObjectParameter("CENTROCUSTO", cENTROCUSTO) :
                new ObjectParameter("CENTROCUSTO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_ALTERAPESSOA_1", mATRICULAParameter, sENHAParameter, nOMEParameter, cENTROCUSTOParameter);
        }
    
        public virtual int UP_ALTERASUPERVISOR(string pIS, string iDENTIFICACAO, string nOME, string sENHA, Nullable<bool> pERMISSAOPROGRAMACOESTECNICAS, Nullable<bool> pERMISSAODATAHORA, Nullable<bool> pERMISSAOPENDRIVE)
        {
            var pISParameter = pIS != null ?
                new ObjectParameter("PIS", pIS) :
                new ObjectParameter("PIS", typeof(string));
    
            var iDENTIFICACAOParameter = iDENTIFICACAO != null ?
                new ObjectParameter("IDENTIFICACAO", iDENTIFICACAO) :
                new ObjectParameter("IDENTIFICACAO", typeof(string));
    
            var nOMEParameter = nOME != null ?
                new ObjectParameter("NOME", nOME) :
                new ObjectParameter("NOME", typeof(string));
    
            var sENHAParameter = sENHA != null ?
                new ObjectParameter("SENHA", sENHA) :
                new ObjectParameter("SENHA", typeof(string));
    
            var pERMISSAOPROGRAMACOESTECNICASParameter = pERMISSAOPROGRAMACOESTECNICAS.HasValue ?
                new ObjectParameter("PERMISSAOPROGRAMACOESTECNICAS", pERMISSAOPROGRAMACOESTECNICAS) :
                new ObjectParameter("PERMISSAOPROGRAMACOESTECNICAS", typeof(bool));
    
            var pERMISSAODATAHORAParameter = pERMISSAODATAHORA.HasValue ?
                new ObjectParameter("PERMISSAODATAHORA", pERMISSAODATAHORA) :
                new ObjectParameter("PERMISSAODATAHORA", typeof(bool));
    
            var pERMISSAOPENDRIVEParameter = pERMISSAOPENDRIVE.HasValue ?
                new ObjectParameter("PERMISSAOPENDRIVE", pERMISSAOPENDRIVE) :
                new ObjectParameter("PERMISSAOPENDRIVE", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_ALTERASUPERVISOR", pISParameter, iDENTIFICACAOParameter, nOMEParameter, sENHAParameter, pERMISSAOPROGRAMACOESTECNICASParameter, pERMISSAODATAHORAParameter, pERMISSAOPENDRIVEParameter);
        }
    
        public virtual int UP_ALTERASUPERVISOR_1(string pIS, string iDENTIFICACAO, string nOME, string sENHA, Nullable<bool> pERMISSAOPROGRAMACOESTECNICAS, Nullable<bool> pERMISSAODATAHORA, Nullable<bool> pERMISSAOPENDRIVE, Nullable<bool> pERMISSAOTROCABOBINA)
        {
            var pISParameter = pIS != null ?
                new ObjectParameter("PIS", pIS) :
                new ObjectParameter("PIS", typeof(string));
    
            var iDENTIFICACAOParameter = iDENTIFICACAO != null ?
                new ObjectParameter("IDENTIFICACAO", iDENTIFICACAO) :
                new ObjectParameter("IDENTIFICACAO", typeof(string));
    
            var nOMEParameter = nOME != null ?
                new ObjectParameter("NOME", nOME) :
                new ObjectParameter("NOME", typeof(string));
    
            var sENHAParameter = sENHA != null ?
                new ObjectParameter("SENHA", sENHA) :
                new ObjectParameter("SENHA", typeof(string));
    
            var pERMISSAOPROGRAMACOESTECNICASParameter = pERMISSAOPROGRAMACOESTECNICAS.HasValue ?
                new ObjectParameter("PERMISSAOPROGRAMACOESTECNICAS", pERMISSAOPROGRAMACOESTECNICAS) :
                new ObjectParameter("PERMISSAOPROGRAMACOESTECNICAS", typeof(bool));
    
            var pERMISSAODATAHORAParameter = pERMISSAODATAHORA.HasValue ?
                new ObjectParameter("PERMISSAODATAHORA", pERMISSAODATAHORA) :
                new ObjectParameter("PERMISSAODATAHORA", typeof(bool));
    
            var pERMISSAOPENDRIVEParameter = pERMISSAOPENDRIVE.HasValue ?
                new ObjectParameter("PERMISSAOPENDRIVE", pERMISSAOPENDRIVE) :
                new ObjectParameter("PERMISSAOPENDRIVE", typeof(bool));
    
            var pERMISSAOTROCABOBINAParameter = pERMISSAOTROCABOBINA.HasValue ?
                new ObjectParameter("PERMISSAOTROCABOBINA", pERMISSAOTROCABOBINA) :
                new ObjectParameter("PERMISSAOTROCABOBINA", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_ALTERASUPERVISOR_1", pISParameter, iDENTIFICACAOParameter, nOMEParameter, sENHAParameter, pERMISSAOPROGRAMACOESTECNICASParameter, pERMISSAODATAHORAParameter, pERMISSAOPENDRIVEParameter, pERMISSAOTROCABOBINAParameter);
        }
    
        public virtual int UP_ALTERASUPERVISOR_2(string pIS, string iDENTIFICACAO, string nOME, string sENHA, Nullable<bool> pERMISSAOPROGRAMACOESTECNICAS, Nullable<bool> pERMISSAODATAHORA, Nullable<bool> pERMISSAOPENDRIVE, Nullable<bool> pERMISSAOTROCABOBINA, string cPF)
        {
            var pISParameter = pIS != null ?
                new ObjectParameter("PIS", pIS) :
                new ObjectParameter("PIS", typeof(string));
    
            var iDENTIFICACAOParameter = iDENTIFICACAO != null ?
                new ObjectParameter("IDENTIFICACAO", iDENTIFICACAO) :
                new ObjectParameter("IDENTIFICACAO", typeof(string));
    
            var nOMEParameter = nOME != null ?
                new ObjectParameter("NOME", nOME) :
                new ObjectParameter("NOME", typeof(string));
    
            var sENHAParameter = sENHA != null ?
                new ObjectParameter("SENHA", sENHA) :
                new ObjectParameter("SENHA", typeof(string));
    
            var pERMISSAOPROGRAMACOESTECNICASParameter = pERMISSAOPROGRAMACOESTECNICAS.HasValue ?
                new ObjectParameter("PERMISSAOPROGRAMACOESTECNICAS", pERMISSAOPROGRAMACOESTECNICAS) :
                new ObjectParameter("PERMISSAOPROGRAMACOESTECNICAS", typeof(bool));
    
            var pERMISSAODATAHORAParameter = pERMISSAODATAHORA.HasValue ?
                new ObjectParameter("PERMISSAODATAHORA", pERMISSAODATAHORA) :
                new ObjectParameter("PERMISSAODATAHORA", typeof(bool));
    
            var pERMISSAOPENDRIVEParameter = pERMISSAOPENDRIVE.HasValue ?
                new ObjectParameter("PERMISSAOPENDRIVE", pERMISSAOPENDRIVE) :
                new ObjectParameter("PERMISSAOPENDRIVE", typeof(bool));
    
            var pERMISSAOTROCABOBINAParameter = pERMISSAOTROCABOBINA.HasValue ?
                new ObjectParameter("PERMISSAOTROCABOBINA", pERMISSAOTROCABOBINA) :
                new ObjectParameter("PERMISSAOTROCABOBINA", typeof(bool));
    
            var cPFParameter = cPF != null ?
                new ObjectParameter("CPF", cPF) :
                new ObjectParameter("CPF", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_ALTERASUPERVISOR_2", pISParameter, iDENTIFICACAOParameter, nOMEParameter, sENHAParameter, pERMISSAOPROGRAMACOESTECNICASParameter, pERMISSAODATAHORAParameter, pERMISSAOPENDRIVEParameter, pERMISSAOTROCABOBINAParameter, cPFParameter);
        }
    
        public virtual ObjectResult<Nullable<System.DateTime>> UP_APAGATABELATEMP(string nOMETABELA)
        {
            var nOMETABELAParameter = nOMETABELA != null ?
                new ObjectParameter("NOMETABELA", nOMETABELA) :
                new ObjectParameter("NOMETABELA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.DateTime>>("UP_APAGATABELATEMP", nOMETABELAParameter);
        }
    
        public virtual int UP_ASSOCIAPESSOARELOGIO(string mATRICULA, Nullable<int> iDRELOGIO)
        {
            var mATRICULAParameter = mATRICULA != null ?
                new ObjectParameter("MATRICULA", mATRICULA) :
                new ObjectParameter("MATRICULA", typeof(string));
    
            var iDRELOGIOParameter = iDRELOGIO.HasValue ?
                new ObjectParameter("IDRELOGIO", iDRELOGIO) :
                new ObjectParameter("IDRELOGIO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_ASSOCIAPESSOARELOGIO", mATRICULAParameter, iDRELOGIOParameter);
        }
    
        public virtual int UP_ASSOCIAPESSOARELOGIO_1(string mATRICULA, Nullable<int> iDRELOGIO, Nullable<int> cODIGOMENSAGEMUSUARIO, Nullable<int> iDJORNADA, Nullable<short> pRIMEIRAFAIXA, Nullable<short> sEGUNDAFAIXA, Nullable<short> tERCEIRAFAIXA, Nullable<short> qUARTAFAIXA, Nullable<short> qUINTAFAIXA, Nullable<short> sEXTAFAIXA)
        {
            var mATRICULAParameter = mATRICULA != null ?
                new ObjectParameter("MATRICULA", mATRICULA) :
                new ObjectParameter("MATRICULA", typeof(string));
    
            var iDRELOGIOParameter = iDRELOGIO.HasValue ?
                new ObjectParameter("IDRELOGIO", iDRELOGIO) :
                new ObjectParameter("IDRELOGIO", typeof(int));
    
            var cODIGOMENSAGEMUSUARIOParameter = cODIGOMENSAGEMUSUARIO.HasValue ?
                new ObjectParameter("CODIGOMENSAGEMUSUARIO", cODIGOMENSAGEMUSUARIO) :
                new ObjectParameter("CODIGOMENSAGEMUSUARIO", typeof(int));
    
            var iDJORNADAParameter = iDJORNADA.HasValue ?
                new ObjectParameter("IDJORNADA", iDJORNADA) :
                new ObjectParameter("IDJORNADA", typeof(int));
    
            var pRIMEIRAFAIXAParameter = pRIMEIRAFAIXA.HasValue ?
                new ObjectParameter("PRIMEIRAFAIXA", pRIMEIRAFAIXA) :
                new ObjectParameter("PRIMEIRAFAIXA", typeof(short));
    
            var sEGUNDAFAIXAParameter = sEGUNDAFAIXA.HasValue ?
                new ObjectParameter("SEGUNDAFAIXA", sEGUNDAFAIXA) :
                new ObjectParameter("SEGUNDAFAIXA", typeof(short));
    
            var tERCEIRAFAIXAParameter = tERCEIRAFAIXA.HasValue ?
                new ObjectParameter("TERCEIRAFAIXA", tERCEIRAFAIXA) :
                new ObjectParameter("TERCEIRAFAIXA", typeof(short));
    
            var qUARTAFAIXAParameter = qUARTAFAIXA.HasValue ?
                new ObjectParameter("QUARTAFAIXA", qUARTAFAIXA) :
                new ObjectParameter("QUARTAFAIXA", typeof(short));
    
            var qUINTAFAIXAParameter = qUINTAFAIXA.HasValue ?
                new ObjectParameter("QUINTAFAIXA", qUINTAFAIXA) :
                new ObjectParameter("QUINTAFAIXA", typeof(short));
    
            var sEXTAFAIXAParameter = sEXTAFAIXA.HasValue ?
                new ObjectParameter("SEXTAFAIXA", sEXTAFAIXA) :
                new ObjectParameter("SEXTAFAIXA", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_ASSOCIAPESSOARELOGIO_1", mATRICULAParameter, iDRELOGIOParameter, cODIGOMENSAGEMUSUARIOParameter, iDJORNADAParameter, pRIMEIRAFAIXAParameter, sEGUNDAFAIXAParameter, tERCEIRAFAIXAParameter, qUARTAFAIXAParameter, qUINTAFAIXAParameter, sEXTAFAIXAParameter);
        }
    
        public virtual int UP_ASSOCIASUPRELPORIDENT(string iDENTIFICACAO, Nullable<int> iDRELOGIO)
        {
            var iDENTIFICACAOParameter = iDENTIFICACAO != null ?
                new ObjectParameter("IDENTIFICACAO", iDENTIFICACAO) :
                new ObjectParameter("IDENTIFICACAO", typeof(string));
    
            var iDRELOGIOParameter = iDRELOGIO.HasValue ?
                new ObjectParameter("IDRELOGIO", iDRELOGIO) :
                new ObjectParameter("IDRELOGIO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_ASSOCIASUPRELPORIDENT", iDENTIFICACAOParameter, iDRELOGIOParameter);
        }
    
        public virtual int UP_ASSOCIASUPRELPORPIS(string pIS, Nullable<int> iDRELOGIO)
        {
            var pISParameter = pIS != null ?
                new ObjectParameter("PIS", pIS) :
                new ObjectParameter("PIS", typeof(string));
    
            var iDRELOGIOParameter = iDRELOGIO.HasValue ?
                new ObjectParameter("IDRELOGIO", iDRELOGIO) :
                new ObjectParameter("IDRELOGIO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_ASSOCIASUPRELPORPIS", pISParameter, iDRELOGIOParameter);
        }
    
        public virtual int UP_ASSOCIATODOS(string mATRICULA)
        {
            var mATRICULAParameter = mATRICULA != null ?
                new ObjectParameter("MATRICULA", mATRICULA) :
                new ObjectParameter("MATRICULA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_ASSOCIATODOS", mATRICULAParameter);
        }
    
        public virtual int UP_CRIATABELAFILTRO(ObjectParameter nOMETABELA)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_CRIATABELAFILTRO", nOMETABELA);
        }
    
        public virtual int UP_DESASSOCIAPESSOARELOGIO(string mATRICULA, Nullable<int> iDRELOGIO)
        {
            var mATRICULAParameter = mATRICULA != null ?
                new ObjectParameter("MATRICULA", mATRICULA) :
                new ObjectParameter("MATRICULA", typeof(string));
    
            var iDRELOGIOParameter = iDRELOGIO.HasValue ?
                new ObjectParameter("IDRELOGIO", iDRELOGIO) :
                new ObjectParameter("IDRELOGIO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_DESASSOCIAPESSOARELOGIO", mATRICULAParameter, iDRELOGIOParameter);
        }
    
        public virtual int UP_DESASSOCIASUPRELPORIDENT(string iDENTIFICACAO, Nullable<int> iDRELOGIO)
        {
            var iDENTIFICACAOParameter = iDENTIFICACAO != null ?
                new ObjectParameter("IDENTIFICACAO", iDENTIFICACAO) :
                new ObjectParameter("IDENTIFICACAO", typeof(string));
    
            var iDRELOGIOParameter = iDRELOGIO.HasValue ?
                new ObjectParameter("IDRELOGIO", iDRELOGIO) :
                new ObjectParameter("IDRELOGIO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_DESASSOCIASUPRELPORIDENT", iDENTIFICACAOParameter, iDRELOGIOParameter);
        }
    
        public virtual int UP_DESASSOCIASUPRELPORPIS(string pIS, Nullable<int> iDRELOGIO)
        {
            var pISParameter = pIS != null ?
                new ObjectParameter("PIS", pIS) :
                new ObjectParameter("PIS", typeof(string));
    
            var iDRELOGIOParameter = iDRELOGIO.HasValue ?
                new ObjectParameter("IDRELOGIO", iDRELOGIO) :
                new ObjectParameter("IDRELOGIO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_DESASSOCIASUPRELPORPIS", pISParameter, iDRELOGIOParameter);
        }
    
        public virtual int UP_ENVIARPESSOASAP(string pIS, string mATRICULA, string nOME, string cARTAOTITULAR, string cARTAOPROVISORIO, Nullable<System.DateTime> iNICIOCARTAOPROVISORIO, Nullable<System.DateTime> fIMCARTAOPROVISORIO, Nullable<bool> oPERACAO)
        {
            var pISParameter = pIS != null ?
                new ObjectParameter("PIS", pIS) :
                new ObjectParameter("PIS", typeof(string));
    
            var mATRICULAParameter = mATRICULA != null ?
                new ObjectParameter("MATRICULA", mATRICULA) :
                new ObjectParameter("MATRICULA", typeof(string));
    
            var nOMEParameter = nOME != null ?
                new ObjectParameter("NOME", nOME) :
                new ObjectParameter("NOME", typeof(string));
    
            var cARTAOTITULARParameter = cARTAOTITULAR != null ?
                new ObjectParameter("CARTAOTITULAR", cARTAOTITULAR) :
                new ObjectParameter("CARTAOTITULAR", typeof(string));
    
            var cARTAOPROVISORIOParameter = cARTAOPROVISORIO != null ?
                new ObjectParameter("CARTAOPROVISORIO", cARTAOPROVISORIO) :
                new ObjectParameter("CARTAOPROVISORIO", typeof(string));
    
            var iNICIOCARTAOPROVISORIOParameter = iNICIOCARTAOPROVISORIO.HasValue ?
                new ObjectParameter("INICIOCARTAOPROVISORIO", iNICIOCARTAOPROVISORIO) :
                new ObjectParameter("INICIOCARTAOPROVISORIO", typeof(System.DateTime));
    
            var fIMCARTAOPROVISORIOParameter = fIMCARTAOPROVISORIO.HasValue ?
                new ObjectParameter("FIMCARTAOPROVISORIO", fIMCARTAOPROVISORIO) :
                new ObjectParameter("FIMCARTAOPROVISORIO", typeof(System.DateTime));
    
            var oPERACAOParameter = oPERACAO.HasValue ?
                new ObjectParameter("OPERACAO", oPERACAO) :
                new ObjectParameter("OPERACAO", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_ENVIARPESSOASAP", pISParameter, mATRICULAParameter, nOMEParameter, cARTAOTITULARParameter, cARTAOPROVISORIOParameter, iNICIOCARTAOPROVISORIOParameter, fIMCARTAOPROVISORIOParameter, oPERACAOParameter);
        }
    
        public virtual int UP_ENVIARPESSOASAP_1(string pIS, string mATRICULA, string nOME, string cARTAOTITULAR, string cARTAOPROVISORIO, Nullable<System.DateTime> iNICIOCARTAOPROVISORIO, Nullable<System.DateTime> fIMCARTAOPROVISORIO, Nullable<bool> oPERACAO, string eQUIPAMENTOS)
        {
            var pISParameter = pIS != null ?
                new ObjectParameter("PIS", pIS) :
                new ObjectParameter("PIS", typeof(string));
    
            var mATRICULAParameter = mATRICULA != null ?
                new ObjectParameter("MATRICULA", mATRICULA) :
                new ObjectParameter("MATRICULA", typeof(string));
    
            var nOMEParameter = nOME != null ?
                new ObjectParameter("NOME", nOME) :
                new ObjectParameter("NOME", typeof(string));
    
            var cARTAOTITULARParameter = cARTAOTITULAR != null ?
                new ObjectParameter("CARTAOTITULAR", cARTAOTITULAR) :
                new ObjectParameter("CARTAOTITULAR", typeof(string));
    
            var cARTAOPROVISORIOParameter = cARTAOPROVISORIO != null ?
                new ObjectParameter("CARTAOPROVISORIO", cARTAOPROVISORIO) :
                new ObjectParameter("CARTAOPROVISORIO", typeof(string));
    
            var iNICIOCARTAOPROVISORIOParameter = iNICIOCARTAOPROVISORIO.HasValue ?
                new ObjectParameter("INICIOCARTAOPROVISORIO", iNICIOCARTAOPROVISORIO) :
                new ObjectParameter("INICIOCARTAOPROVISORIO", typeof(System.DateTime));
    
            var fIMCARTAOPROVISORIOParameter = fIMCARTAOPROVISORIO.HasValue ?
                new ObjectParameter("FIMCARTAOPROVISORIO", fIMCARTAOPROVISORIO) :
                new ObjectParameter("FIMCARTAOPROVISORIO", typeof(System.DateTime));
    
            var oPERACAOParameter = oPERACAO.HasValue ?
                new ObjectParameter("OPERACAO", oPERACAO) :
                new ObjectParameter("OPERACAO", typeof(bool));
    
            var eQUIPAMENTOSParameter = eQUIPAMENTOS != null ?
                new ObjectParameter("EQUIPAMENTOS", eQUIPAMENTOS) :
                new ObjectParameter("EQUIPAMENTOS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_ENVIARPESSOASAP_1", pISParameter, mATRICULAParameter, nOMEParameter, cARTAOTITULARParameter, cARTAOPROVISORIOParameter, iNICIOCARTAOPROVISORIOParameter, fIMCARTAOPROVISORIOParameter, oPERACAOParameter, eQUIPAMENTOSParameter);
        }
    
        public virtual int UP_EXCLUICARTAO(string mATRICULA, string cARTAO)
        {
            var mATRICULAParameter = mATRICULA != null ?
                new ObjectParameter("MATRICULA", mATRICULA) :
                new ObjectParameter("MATRICULA", typeof(string));
    
            var cARTAOParameter = cARTAO != null ?
                new ObjectParameter("CARTAO", cARTAO) :
                new ObjectParameter("CARTAO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_EXCLUICARTAO", mATRICULAParameter, cARTAOParameter);
        }
    
        public virtual int UP_EXCLUICENTROCUSTO(string cODIGOCENTROCUSTO)
        {
            var cODIGOCENTROCUSTOParameter = cODIGOCENTROCUSTO != null ?
                new ObjectParameter("CODIGOCENTROCUSTO", cODIGOCENTROCUSTO) :
                new ObjectParameter("CODIGOCENTROCUSTO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_EXCLUICENTROCUSTO", cODIGOCENTROCUSTOParameter);
        }
    
        public virtual int UP_EXCLUIPESSOA(string mATRICULA)
        {
            var mATRICULAParameter = mATRICULA != null ?
                new ObjectParameter("MATRICULA", mATRICULA) :
                new ObjectParameter("MATRICULA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_EXCLUIPESSOA", mATRICULAParameter);
        }
    
        public virtual int UP_EXCLUISUPERVISORPORIDENT(string iDENTIFICACAO)
        {
            var iDENTIFICACAOParameter = iDENTIFICACAO != null ?
                new ObjectParameter("IDENTIFICACAO", iDENTIFICACAO) :
                new ObjectParameter("IDENTIFICACAO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_EXCLUISUPERVISORPORIDENT", iDENTIFICACAOParameter);
        }
    
        public virtual int UP_EXCLUISUPERVISORPORPIS(string pIS)
        {
            var pISParameter = pIS != null ?
                new ObjectParameter("PIS", pIS) :
                new ObjectParameter("PIS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_EXCLUISUPERVISORPORPIS", pISParameter);
        }
    
        public virtual int UP_EXCLUITEMPLATE(Nullable<int> iDTEMPLATE)
        {
            var iDTEMPLATEParameter = iDTEMPLATE.HasValue ?
                new ObjectParameter("IDTEMPLATE", iDTEMPLATE) :
                new ObjectParameter("IDTEMPLATE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_EXCLUITEMPLATE", iDTEMPLATEParameter);
        }
    
        public virtual int UP_EXCLUITEMPLATEPORMATRICULA(string mATRICULA)
        {
            var mATRICULAParameter = mATRICULA != null ?
                new ObjectParameter("MATRICULA", mATRICULA) :
                new ObjectParameter("MATRICULA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_EXCLUITEMPLATEPORMATRICULA", mATRICULAParameter);
        }
    
        public virtual int UP_INCLUICARTAO(string mATRICULA, string cARTAO, Nullable<byte> tIPOTECNOLOGIA)
        {
            var mATRICULAParameter = mATRICULA != null ?
                new ObjectParameter("MATRICULA", mATRICULA) :
                new ObjectParameter("MATRICULA", typeof(string));
    
            var cARTAOParameter = cARTAO != null ?
                new ObjectParameter("CARTAO", cARTAO) :
                new ObjectParameter("CARTAO", typeof(string));
    
            var tIPOTECNOLOGIAParameter = tIPOTECNOLOGIA.HasValue ?
                new ObjectParameter("TIPOTECNOLOGIA", tIPOTECNOLOGIA) :
                new ObjectParameter("TIPOTECNOLOGIA", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_INCLUICARTAO", mATRICULAParameter, cARTAOParameter, tIPOTECNOLOGIAParameter);
        }
    
        public virtual int UP_INCLUICARTAO_1(string mATRICULA, string cARTAO, Nullable<byte> tIPOTECNOLOGIA, Nullable<System.DateTime> dATASINCRONIZACAO)
        {
            var mATRICULAParameter = mATRICULA != null ?
                new ObjectParameter("MATRICULA", mATRICULA) :
                new ObjectParameter("MATRICULA", typeof(string));
    
            var cARTAOParameter = cARTAO != null ?
                new ObjectParameter("CARTAO", cARTAO) :
                new ObjectParameter("CARTAO", typeof(string));
    
            var tIPOTECNOLOGIAParameter = tIPOTECNOLOGIA.HasValue ?
                new ObjectParameter("TIPOTECNOLOGIA", tIPOTECNOLOGIA) :
                new ObjectParameter("TIPOTECNOLOGIA", typeof(byte));
    
            var dATASINCRONIZACAOParameter = dATASINCRONIZACAO.HasValue ?
                new ObjectParameter("DATASINCRONIZACAO", dATASINCRONIZACAO) :
                new ObjectParameter("DATASINCRONIZACAO", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_INCLUICARTAO_1", mATRICULAParameter, cARTAOParameter, tIPOTECNOLOGIAParameter, dATASINCRONIZACAOParameter);
        }
    
        public virtual int UP_INCLUICARTAO_2(string mATRICULA, string cARTAO, Nullable<byte> tIPOTECNOLOGIA, string cODIGOALTERNATIVO, string vIA, Nullable<System.DateTime> iNICIOPROVISORIO, Nullable<System.DateTime> fIMPROVISORIO)
        {
            var mATRICULAParameter = mATRICULA != null ?
                new ObjectParameter("MATRICULA", mATRICULA) :
                new ObjectParameter("MATRICULA", typeof(string));
    
            var cARTAOParameter = cARTAO != null ?
                new ObjectParameter("CARTAO", cARTAO) :
                new ObjectParameter("CARTAO", typeof(string));
    
            var tIPOTECNOLOGIAParameter = tIPOTECNOLOGIA.HasValue ?
                new ObjectParameter("TIPOTECNOLOGIA", tIPOTECNOLOGIA) :
                new ObjectParameter("TIPOTECNOLOGIA", typeof(byte));
    
            var cODIGOALTERNATIVOParameter = cODIGOALTERNATIVO != null ?
                new ObjectParameter("CODIGOALTERNATIVO", cODIGOALTERNATIVO) :
                new ObjectParameter("CODIGOALTERNATIVO", typeof(string));
    
            var vIAParameter = vIA != null ?
                new ObjectParameter("VIA", vIA) :
                new ObjectParameter("VIA", typeof(string));
    
            var iNICIOPROVISORIOParameter = iNICIOPROVISORIO.HasValue ?
                new ObjectParameter("INICIOPROVISORIO", iNICIOPROVISORIO) :
                new ObjectParameter("INICIOPROVISORIO", typeof(System.DateTime));
    
            var fIMPROVISORIOParameter = fIMPROVISORIO.HasValue ?
                new ObjectParameter("FIMPROVISORIO", fIMPROVISORIO) :
                new ObjectParameter("FIMPROVISORIO", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_INCLUICARTAO_2", mATRICULAParameter, cARTAOParameter, tIPOTECNOLOGIAParameter, cODIGOALTERNATIVOParameter, vIAParameter, iNICIOPROVISORIOParameter, fIMPROVISORIOParameter);
        }
    
        public virtual int UP_INCLUICARTAO_3(string mATRICULA, string cARTAO, Nullable<byte> tIPOTECNOLOGIA, string cODIGOALTERNATIVO, string vIA, Nullable<System.DateTime> iNICIOPROVISORIO, Nullable<System.DateTime> fIMPROVISORIO, Nullable<bool> uSOIDENTIFICACAOBIOMETRICA)
        {
            var mATRICULAParameter = mATRICULA != null ?
                new ObjectParameter("MATRICULA", mATRICULA) :
                new ObjectParameter("MATRICULA", typeof(string));
    
            var cARTAOParameter = cARTAO != null ?
                new ObjectParameter("CARTAO", cARTAO) :
                new ObjectParameter("CARTAO", typeof(string));
    
            var tIPOTECNOLOGIAParameter = tIPOTECNOLOGIA.HasValue ?
                new ObjectParameter("TIPOTECNOLOGIA", tIPOTECNOLOGIA) :
                new ObjectParameter("TIPOTECNOLOGIA", typeof(byte));
    
            var cODIGOALTERNATIVOParameter = cODIGOALTERNATIVO != null ?
                new ObjectParameter("CODIGOALTERNATIVO", cODIGOALTERNATIVO) :
                new ObjectParameter("CODIGOALTERNATIVO", typeof(string));
    
            var vIAParameter = vIA != null ?
                new ObjectParameter("VIA", vIA) :
                new ObjectParameter("VIA", typeof(string));
    
            var iNICIOPROVISORIOParameter = iNICIOPROVISORIO.HasValue ?
                new ObjectParameter("INICIOPROVISORIO", iNICIOPROVISORIO) :
                new ObjectParameter("INICIOPROVISORIO", typeof(System.DateTime));
    
            var fIMPROVISORIOParameter = fIMPROVISORIO.HasValue ?
                new ObjectParameter("FIMPROVISORIO", fIMPROVISORIO) :
                new ObjectParameter("FIMPROVISORIO", typeof(System.DateTime));
    
            var uSOIDENTIFICACAOBIOMETRICAParameter = uSOIDENTIFICACAOBIOMETRICA.HasValue ?
                new ObjectParameter("USOIDENTIFICACAOBIOMETRICA", uSOIDENTIFICACAOBIOMETRICA) :
                new ObjectParameter("USOIDENTIFICACAOBIOMETRICA", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_INCLUICARTAO_3", mATRICULAParameter, cARTAOParameter, tIPOTECNOLOGIAParameter, cODIGOALTERNATIVOParameter, vIAParameter, iNICIOPROVISORIOParameter, fIMPROVISORIOParameter, uSOIDENTIFICACAOBIOMETRICAParameter);
        }
    
        public virtual int UP_INCLUICENTROCUSTO(string cODIGOCENTROCUSTO, string dESCRICAO)
        {
            var cODIGOCENTROCUSTOParameter = cODIGOCENTROCUSTO != null ?
                new ObjectParameter("CODIGOCENTROCUSTO", cODIGOCENTROCUSTO) :
                new ObjectParameter("CODIGOCENTROCUSTO", typeof(string));
    
            var dESCRICAOParameter = dESCRICAO != null ?
                new ObjectParameter("DESCRICAO", dESCRICAO) :
                new ObjectParameter("DESCRICAO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_INCLUICENTROCUSTO", cODIGOCENTROCUSTOParameter, dESCRICAOParameter);
        }
    
        public virtual int UP_INCLUIPESSOA(string mATRICULA, string sENHA, string pIS, string nOME)
        {
            var mATRICULAParameter = mATRICULA != null ?
                new ObjectParameter("MATRICULA", mATRICULA) :
                new ObjectParameter("MATRICULA", typeof(string));
    
            var sENHAParameter = sENHA != null ?
                new ObjectParameter("SENHA", sENHA) :
                new ObjectParameter("SENHA", typeof(string));
    
            var pISParameter = pIS != null ?
                new ObjectParameter("PIS", pIS) :
                new ObjectParameter("PIS", typeof(string));
    
            var nOMEParameter = nOME != null ?
                new ObjectParameter("NOME", nOME) :
                new ObjectParameter("NOME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_INCLUIPESSOA", mATRICULAParameter, sENHAParameter, pISParameter, nOMEParameter);
        }
    
        public virtual int UP_INCLUIPESSOA_1(string mATRICULA, string sENHA, string pIS, string nOME, string cENTROCUSTO)
        {
            var mATRICULAParameter = mATRICULA != null ?
                new ObjectParameter("MATRICULA", mATRICULA) :
                new ObjectParameter("MATRICULA", typeof(string));
    
            var sENHAParameter = sENHA != null ?
                new ObjectParameter("SENHA", sENHA) :
                new ObjectParameter("SENHA", typeof(string));
    
            var pISParameter = pIS != null ?
                new ObjectParameter("PIS", pIS) :
                new ObjectParameter("PIS", typeof(string));
    
            var nOMEParameter = nOME != null ?
                new ObjectParameter("NOME", nOME) :
                new ObjectParameter("NOME", typeof(string));
    
            var cENTROCUSTOParameter = cENTROCUSTO != null ?
                new ObjectParameter("CENTROCUSTO", cENTROCUSTO) :
                new ObjectParameter("CENTROCUSTO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_INCLUIPESSOA_1", mATRICULAParameter, sENHAParameter, pISParameter, nOMEParameter, cENTROCUSTOParameter);
        }
    
        public virtual int UP_INCLUIPESSOA_2(string mATRICULA, string sENHA, string pIS, string nOME, string cENTROCUSTO)
        {
            var mATRICULAParameter = mATRICULA != null ?
                new ObjectParameter("MATRICULA", mATRICULA) :
                new ObjectParameter("MATRICULA", typeof(string));
    
            var sENHAParameter = sENHA != null ?
                new ObjectParameter("SENHA", sENHA) :
                new ObjectParameter("SENHA", typeof(string));
    
            var pISParameter = pIS != null ?
                new ObjectParameter("PIS", pIS) :
                new ObjectParameter("PIS", typeof(string));
    
            var nOMEParameter = nOME != null ?
                new ObjectParameter("NOME", nOME) :
                new ObjectParameter("NOME", typeof(string));
    
            var cENTROCUSTOParameter = cENTROCUSTO != null ?
                new ObjectParameter("CENTROCUSTO", cENTROCUSTO) :
                new ObjectParameter("CENTROCUSTO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_INCLUIPESSOA_2", mATRICULAParameter, sENHAParameter, pISParameter, nOMEParameter, cENTROCUSTOParameter);
        }
    
        public virtual int UP_INCLUISINCTEMPLATESERVER(Nullable<int> iDPESSOA, Nullable<bool> uSOIDENTIFICACAOBIOMETRICA)
        {
            var iDPESSOAParameter = iDPESSOA.HasValue ?
                new ObjectParameter("IDPESSOA", iDPESSOA) :
                new ObjectParameter("IDPESSOA", typeof(int));
    
            var uSOIDENTIFICACAOBIOMETRICAParameter = uSOIDENTIFICACAOBIOMETRICA.HasValue ?
                new ObjectParameter("USOIDENTIFICACAOBIOMETRICA", uSOIDENTIFICACAOBIOMETRICA) :
                new ObjectParameter("USOIDENTIFICACAOBIOMETRICA", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_INCLUISINCTEMPLATESERVER", iDPESSOAParameter, uSOIDENTIFICACAOBIOMETRICAParameter);
        }
    
        public virtual int UP_INCLUISUPERVISOR(string pIS, string iDENTIFICACAO, string nOME, string sENHA, Nullable<bool> pERMISSAOPROGRAMACOESTECNICAS, Nullable<bool> pERMISSAODATAHORA, Nullable<bool> pERMISSAOPENDRIVE)
        {
            var pISParameter = pIS != null ?
                new ObjectParameter("PIS", pIS) :
                new ObjectParameter("PIS", typeof(string));
    
            var iDENTIFICACAOParameter = iDENTIFICACAO != null ?
                new ObjectParameter("IDENTIFICACAO", iDENTIFICACAO) :
                new ObjectParameter("IDENTIFICACAO", typeof(string));
    
            var nOMEParameter = nOME != null ?
                new ObjectParameter("NOME", nOME) :
                new ObjectParameter("NOME", typeof(string));
    
            var sENHAParameter = sENHA != null ?
                new ObjectParameter("SENHA", sENHA) :
                new ObjectParameter("SENHA", typeof(string));
    
            var pERMISSAOPROGRAMACOESTECNICASParameter = pERMISSAOPROGRAMACOESTECNICAS.HasValue ?
                new ObjectParameter("PERMISSAOPROGRAMACOESTECNICAS", pERMISSAOPROGRAMACOESTECNICAS) :
                new ObjectParameter("PERMISSAOPROGRAMACOESTECNICAS", typeof(bool));
    
            var pERMISSAODATAHORAParameter = pERMISSAODATAHORA.HasValue ?
                new ObjectParameter("PERMISSAODATAHORA", pERMISSAODATAHORA) :
                new ObjectParameter("PERMISSAODATAHORA", typeof(bool));
    
            var pERMISSAOPENDRIVEParameter = pERMISSAOPENDRIVE.HasValue ?
                new ObjectParameter("PERMISSAOPENDRIVE", pERMISSAOPENDRIVE) :
                new ObjectParameter("PERMISSAOPENDRIVE", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_INCLUISUPERVISOR", pISParameter, iDENTIFICACAOParameter, nOMEParameter, sENHAParameter, pERMISSAOPROGRAMACOESTECNICASParameter, pERMISSAODATAHORAParameter, pERMISSAOPENDRIVEParameter);
        }
    
        public virtual int UP_INCLUISUPERVISOR_1(string pIS, string iDENTIFICACAO, string nOME, string sENHA, Nullable<bool> pERMISSAOPROGRAMACOESTECNICAS, Nullable<bool> pERMISSAODATAHORA, Nullable<bool> pERMISSAOPENDRIVE, Nullable<bool> pERMISSAOTROCABOBINA)
        {
            var pISParameter = pIS != null ?
                new ObjectParameter("PIS", pIS) :
                new ObjectParameter("PIS", typeof(string));
    
            var iDENTIFICACAOParameter = iDENTIFICACAO != null ?
                new ObjectParameter("IDENTIFICACAO", iDENTIFICACAO) :
                new ObjectParameter("IDENTIFICACAO", typeof(string));
    
            var nOMEParameter = nOME != null ?
                new ObjectParameter("NOME", nOME) :
                new ObjectParameter("NOME", typeof(string));
    
            var sENHAParameter = sENHA != null ?
                new ObjectParameter("SENHA", sENHA) :
                new ObjectParameter("SENHA", typeof(string));
    
            var pERMISSAOPROGRAMACOESTECNICASParameter = pERMISSAOPROGRAMACOESTECNICAS.HasValue ?
                new ObjectParameter("PERMISSAOPROGRAMACOESTECNICAS", pERMISSAOPROGRAMACOESTECNICAS) :
                new ObjectParameter("PERMISSAOPROGRAMACOESTECNICAS", typeof(bool));
    
            var pERMISSAODATAHORAParameter = pERMISSAODATAHORA.HasValue ?
                new ObjectParameter("PERMISSAODATAHORA", pERMISSAODATAHORA) :
                new ObjectParameter("PERMISSAODATAHORA", typeof(bool));
    
            var pERMISSAOPENDRIVEParameter = pERMISSAOPENDRIVE.HasValue ?
                new ObjectParameter("PERMISSAOPENDRIVE", pERMISSAOPENDRIVE) :
                new ObjectParameter("PERMISSAOPENDRIVE", typeof(bool));
    
            var pERMISSAOTROCABOBINAParameter = pERMISSAOTROCABOBINA.HasValue ?
                new ObjectParameter("PERMISSAOTROCABOBINA", pERMISSAOTROCABOBINA) :
                new ObjectParameter("PERMISSAOTROCABOBINA", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_INCLUISUPERVISOR_1", pISParameter, iDENTIFICACAOParameter, nOMEParameter, sENHAParameter, pERMISSAOPROGRAMACOESTECNICASParameter, pERMISSAODATAHORAParameter, pERMISSAOPENDRIVEParameter, pERMISSAOTROCABOBINAParameter);
        }
    
        public virtual int UP_INCLUISUPERVISOR_2(string pIS, string iDENTIFICACAO, string nOME, string sENHA, Nullable<bool> pERMISSAOPROGRAMACOESTECNICAS, Nullable<bool> pERMISSAODATAHORA, Nullable<bool> pERMISSAOPENDRIVE, Nullable<bool> pERMISSAOTROCABOBINA, string cPF)
        {
            var pISParameter = pIS != null ?
                new ObjectParameter("PIS", pIS) :
                new ObjectParameter("PIS", typeof(string));
    
            var iDENTIFICACAOParameter = iDENTIFICACAO != null ?
                new ObjectParameter("IDENTIFICACAO", iDENTIFICACAO) :
                new ObjectParameter("IDENTIFICACAO", typeof(string));
    
            var nOMEParameter = nOME != null ?
                new ObjectParameter("NOME", nOME) :
                new ObjectParameter("NOME", typeof(string));
    
            var sENHAParameter = sENHA != null ?
                new ObjectParameter("SENHA", sENHA) :
                new ObjectParameter("SENHA", typeof(string));
    
            var pERMISSAOPROGRAMACOESTECNICASParameter = pERMISSAOPROGRAMACOESTECNICAS.HasValue ?
                new ObjectParameter("PERMISSAOPROGRAMACOESTECNICAS", pERMISSAOPROGRAMACOESTECNICAS) :
                new ObjectParameter("PERMISSAOPROGRAMACOESTECNICAS", typeof(bool));
    
            var pERMISSAODATAHORAParameter = pERMISSAODATAHORA.HasValue ?
                new ObjectParameter("PERMISSAODATAHORA", pERMISSAODATAHORA) :
                new ObjectParameter("PERMISSAODATAHORA", typeof(bool));
    
            var pERMISSAOPENDRIVEParameter = pERMISSAOPENDRIVE.HasValue ?
                new ObjectParameter("PERMISSAOPENDRIVE", pERMISSAOPENDRIVE) :
                new ObjectParameter("PERMISSAOPENDRIVE", typeof(bool));
    
            var pERMISSAOTROCABOBINAParameter = pERMISSAOTROCABOBINA.HasValue ?
                new ObjectParameter("PERMISSAOTROCABOBINA", pERMISSAOTROCABOBINA) :
                new ObjectParameter("PERMISSAOTROCABOBINA", typeof(bool));
    
            var cPFParameter = cPF != null ?
                new ObjectParameter("CPF", cPF) :
                new ObjectParameter("CPF", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_INCLUISUPERVISOR_2", pISParameter, iDENTIFICACAOParameter, nOMEParameter, sENHAParameter, pERMISSAOPROGRAMACOESTECNICASParameter, pERMISSAODATAHORAParameter, pERMISSAOPENDRIVEParameter, pERMISSAOTROCABOBINAParameter, cPFParameter);
        }
    
        public virtual int UP_INCLUITEMPLATE(Nullable<int> iDPESSOA, string tEMPLATE, Nullable<byte> dEDO1, Nullable<byte> dEDO2, Nullable<byte> sENSOR)
        {
            var iDPESSOAParameter = iDPESSOA.HasValue ?
                new ObjectParameter("IDPESSOA", iDPESSOA) :
                new ObjectParameter("IDPESSOA", typeof(int));
    
            var tEMPLATEParameter = tEMPLATE != null ?
                new ObjectParameter("TEMPLATE", tEMPLATE) :
                new ObjectParameter("TEMPLATE", typeof(string));
    
            var dEDO1Parameter = dEDO1.HasValue ?
                new ObjectParameter("DEDO1", dEDO1) :
                new ObjectParameter("DEDO1", typeof(byte));
    
            var dEDO2Parameter = dEDO2.HasValue ?
                new ObjectParameter("DEDO2", dEDO2) :
                new ObjectParameter("DEDO2", typeof(byte));
    
            var sENSORParameter = sENSOR.HasValue ?
                new ObjectParameter("SENSOR", sENSOR) :
                new ObjectParameter("SENSOR", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_INCLUITEMPLATE", iDPESSOAParameter, tEMPLATEParameter, dEDO1Parameter, dEDO2Parameter, sENSORParameter);
        }
    
        public virtual int UP_INCLUITEMPLATEPORMATRICULA(string mATRICULA, string tEMPLATE, Nullable<byte> dEDO1, Nullable<byte> dEDO2, Nullable<byte> sENSOR)
        {
            var mATRICULAParameter = mATRICULA != null ?
                new ObjectParameter("MATRICULA", mATRICULA) :
                new ObjectParameter("MATRICULA", typeof(string));
    
            var tEMPLATEParameter = tEMPLATE != null ?
                new ObjectParameter("TEMPLATE", tEMPLATE) :
                new ObjectParameter("TEMPLATE", typeof(string));
    
            var dEDO1Parameter = dEDO1.HasValue ?
                new ObjectParameter("DEDO1", dEDO1) :
                new ObjectParameter("DEDO1", typeof(byte));
    
            var dEDO2Parameter = dEDO2.HasValue ?
                new ObjectParameter("DEDO2", dEDO2) :
                new ObjectParameter("DEDO2", typeof(byte));
    
            var sENSORParameter = sENSOR.HasValue ?
                new ObjectParameter("SENSOR", sENSOR) :
                new ObjectParameter("SENSOR", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_INCLUITEMPLATEPORMATRICULA", mATRICULAParameter, tEMPLATEParameter, dEDO1Parameter, dEDO2Parameter, sENSORParameter);
        }
    
        public virtual int UP_INSERETABELAFILTRO(string nOMETABELA, Nullable<int> vALOR)
        {
            var nOMETABELAParameter = nOMETABELA != null ?
                new ObjectParameter("NOMETABELA", nOMETABELA) :
                new ObjectParameter("NOMETABELA", typeof(string));
    
            var vALORParameter = vALOR.HasValue ?
                new ObjectParameter("VALOR", vALOR) :
                new ObjectParameter("VALOR", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_INSERETABELAFILTRO", nOMETABELAParameter, vALORParameter);
        }
    
        public virtual int UP_REL_HISTORICOSTATUSRELOGIO(string fILTRORELOGIO, Nullable<bool> bOBINAPOUCOPAPEL, Nullable<bool> bOBINASEMPAPEL, Nullable<bool> gERANDOAFD, Nullable<bool> gERANDORIM, string dATAINICIO, string dATAFIM)
        {
            var fILTRORELOGIOParameter = fILTRORELOGIO != null ?
                new ObjectParameter("FILTRORELOGIO", fILTRORELOGIO) :
                new ObjectParameter("FILTRORELOGIO", typeof(string));
    
            var bOBINAPOUCOPAPELParameter = bOBINAPOUCOPAPEL.HasValue ?
                new ObjectParameter("BOBINAPOUCOPAPEL", bOBINAPOUCOPAPEL) :
                new ObjectParameter("BOBINAPOUCOPAPEL", typeof(bool));
    
            var bOBINASEMPAPELParameter = bOBINASEMPAPEL.HasValue ?
                new ObjectParameter("BOBINASEMPAPEL", bOBINASEMPAPEL) :
                new ObjectParameter("BOBINASEMPAPEL", typeof(bool));
    
            var gERANDOAFDParameter = gERANDOAFD.HasValue ?
                new ObjectParameter("GERANDOAFD", gERANDOAFD) :
                new ObjectParameter("GERANDOAFD", typeof(bool));
    
            var gERANDORIMParameter = gERANDORIM.HasValue ?
                new ObjectParameter("GERANDORIM", gERANDORIM) :
                new ObjectParameter("GERANDORIM", typeof(bool));
    
            var dATAINICIOParameter = dATAINICIO != null ?
                new ObjectParameter("DATAINICIO", dATAINICIO) :
                new ObjectParameter("DATAINICIO", typeof(string));
    
            var dATAFIMParameter = dATAFIM != null ?
                new ObjectParameter("DATAFIM", dATAFIM) :
                new ObjectParameter("DATAFIM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_REL_HISTORICOSTATUSRELOGIO", fILTRORELOGIOParameter, bOBINAPOUCOPAPELParameter, bOBINASEMPAPELParameter, gERANDOAFDParameter, gERANDORIMParameter, dATAINICIOParameter, dATAFIMParameter);
        }
    
        public virtual int UP_REL_MARCACOES(string fILTRORELOGIOS, string fILTROPESSOAS, Nullable<System.DateTime> dATAINICIAL, Nullable<System.DateTime> dATAFINAL, Nullable<int> oRDEM)
        {
            var fILTRORELOGIOSParameter = fILTRORELOGIOS != null ?
                new ObjectParameter("FILTRORELOGIOS", fILTRORELOGIOS) :
                new ObjectParameter("FILTRORELOGIOS", typeof(string));
    
            var fILTROPESSOASParameter = fILTROPESSOAS != null ?
                new ObjectParameter("FILTROPESSOAS", fILTROPESSOAS) :
                new ObjectParameter("FILTROPESSOAS", typeof(string));
    
            var dATAINICIALParameter = dATAINICIAL.HasValue ?
                new ObjectParameter("DATAINICIAL", dATAINICIAL) :
                new ObjectParameter("DATAINICIAL", typeof(System.DateTime));
    
            var dATAFINALParameter = dATAFINAL.HasValue ?
                new ObjectParameter("DATAFINAL", dATAFINAL) :
                new ObjectParameter("DATAFINAL", typeof(System.DateTime));
    
            var oRDEMParameter = oRDEM.HasValue ?
                new ObjectParameter("ORDEM", oRDEM) :
                new ObjectParameter("ORDEM", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_REL_MARCACOES", fILTRORELOGIOSParameter, fILTROPESSOASParameter, dATAINICIALParameter, dATAFINALParameter, oRDEMParameter);
        }
    
        public virtual int UP_REL_PERMISSOES(string fILTROUSUARIO, Nullable<int> oRDEM)
        {
            var fILTROUSUARIOParameter = fILTROUSUARIO != null ?
                new ObjectParameter("FILTROUSUARIO", fILTROUSUARIO) :
                new ObjectParameter("FILTROUSUARIO", typeof(string));
    
            var oRDEMParameter = oRDEM.HasValue ?
                new ObjectParameter("ORDEM", oRDEM) :
                new ObjectParameter("ORDEM", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_REL_PERMISSOES", fILTROUSUARIOParameter, oRDEMParameter);
        }
    
        public virtual int UP_REL_PERMISSOES_AUX(Nullable<int> iDPERMISSAOPAI, Nullable<byte> nIVEL, Nullable<int> iDUSUARIO, string nOMETABELA)
        {
            var iDPERMISSAOPAIParameter = iDPERMISSAOPAI.HasValue ?
                new ObjectParameter("IDPERMISSAOPAI", iDPERMISSAOPAI) :
                new ObjectParameter("IDPERMISSAOPAI", typeof(int));
    
            var nIVELParameter = nIVEL.HasValue ?
                new ObjectParameter("NIVEL", nIVEL) :
                new ObjectParameter("NIVEL", typeof(byte));
    
            var iDUSUARIOParameter = iDUSUARIO.HasValue ?
                new ObjectParameter("IDUSUARIO", iDUSUARIO) :
                new ObjectParameter("IDUSUARIO", typeof(int));
    
            var nOMETABELAParameter = nOMETABELA != null ?
                new ObjectParameter("NOMETABELA", nOMETABELA) :
                new ObjectParameter("NOMETABELA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_REL_PERMISSOES_AUX", iDPERMISSAOPAIParameter, nIVELParameter, iDUSUARIOParameter, nOMETABELAParameter);
        }
    
        public virtual int UP_REL_PESSOASPORRELOGIO(string fILTRORELOGIOS, Nullable<int> oRDEM)
        {
            var fILTRORELOGIOSParameter = fILTRORELOGIOS != null ?
                new ObjectParameter("FILTRORELOGIOS", fILTRORELOGIOS) :
                new ObjectParameter("FILTRORELOGIOS", typeof(string));
    
            var oRDEMParameter = oRDEM.HasValue ?
                new ObjectParameter("ORDEM", oRDEM) :
                new ObjectParameter("ORDEM", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_REL_PESSOASPORRELOGIO", fILTRORELOGIOSParameter, oRDEMParameter);
        }
    
        public virtual int UP_REL_RELOGIOSPORPESSOA(string fILTROPESSOAS, Nullable<int> oRDEM)
        {
            var fILTROPESSOASParameter = fILTROPESSOAS != null ?
                new ObjectParameter("FILTROPESSOAS", fILTROPESSOAS) :
                new ObjectParameter("FILTROPESSOAS", typeof(string));
    
            var oRDEMParameter = oRDEM.HasValue ?
                new ObjectParameter("ORDEM", oRDEM) :
                new ObjectParameter("ORDEM", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_REL_RELOGIOSPORPESSOA", fILTROPESSOASParameter, oRDEMParameter);
        }
    
        public virtual int UP_REL_RELOGIOSPORSUPERVISOR(string fILTROSUPERVISORES, Nullable<int> oRDEM)
        {
            var fILTROSUPERVISORESParameter = fILTROSUPERVISORES != null ?
                new ObjectParameter("FILTROSUPERVISORES", fILTROSUPERVISORES) :
                new ObjectParameter("FILTROSUPERVISORES", typeof(string));
    
            var oRDEMParameter = oRDEM.HasValue ?
                new ObjectParameter("ORDEM", oRDEM) :
                new ObjectParameter("ORDEM", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_REL_RELOGIOSPORSUPERVISOR", fILTROSUPERVISORESParameter, oRDEMParameter);
        }
    
        public virtual int UP_REL_SUPERVISORESPORRELOGIO(string fILTRORELOGIOS, Nullable<int> oRDEM)
        {
            var fILTRORELOGIOSParameter = fILTRORELOGIOS != null ?
                new ObjectParameter("FILTRORELOGIOS", fILTRORELOGIOS) :
                new ObjectParameter("FILTRORELOGIOS", typeof(string));
    
            var oRDEMParameter = oRDEM.HasValue ?
                new ObjectParameter("ORDEM", oRDEM) :
                new ObjectParameter("ORDEM", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_REL_SUPERVISORESPORRELOGIO", fILTRORELOGIOSParameter, oRDEMParameter);
        }
    
        public virtual int UP_VALIDAPIS(string pIS, ObjectParameter rESULTADO)
        {
            var pISParameter = pIS != null ?
                new ObjectParameter("PIS", pIS) :
                new ObjectParameter("PIS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_VALIDAPIS", pISParameter, rESULTADO);
        }
    }
}
