//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cwkPontoMT.Integracao.Relogios.Dimep
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABELAFUNCIONARIOS
    {
        public long IDTABELAFUNCIONARIOS { get; set; }
        public string MATRICULA { get; set; }
        public string SENHA { get; set; }
        public Nullable<long> PIS { get; set; }
        public string NOME { get; set; }
        public string CARTAO { get; set; }
        public string CENTROCUSTO { get; set; }
        public string NOMEARQUIVO { get; set; }
        public Nullable<int> IDRELOGIO { get; set; }
        public Nullable<int> CODIGOLEITURA { get; set; }
        public Nullable<bool> PROCESSADO { get; set; }
    }
}
