//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cwkPontoMT.Integracao.Relogios.Dimep
{
    using System;
    using System.Collections.Generic;
    
    public partial class TECNOLOGIALEITURA
    {
        public TECNOLOGIALEITURA()
        {
            this.RELOGIOS = new HashSet<RELOGIOS>();
        }
    
        public int IDTECNOLOGIALEITURA { get; set; }
        public Nullable<int> TIPOTECNOLOGIALEITURA { get; set; }
    
        public virtual ICollection<RELOGIOS> RELOGIOS { get; set; }
    }
}
