//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cwkPontoMT.Integracao.Relogios.Dimep
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPOCOMANDO
    {
        public TIPOCOMANDO()
        {
            this.EXECUCAOCOMANDO = new HashSet<EXECUCAOCOMANDO>();
            this.HISTEXECUCAOCOMANDO = new HashSet<HISTEXECUCAOCOMANDO>();
        }
    
        public int IDTIPOCOMANDO { get; set; }
        public string DESCRICAO { get; set; }
    
        public virtual ICollection<EXECUCAOCOMANDO> EXECUCAOCOMANDO { get; set; }
        public virtual ICollection<HISTEXECUCAOCOMANDO> HISTEXECUCAOCOMANDO { get; set; }
    }
}
