//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cwkPontoMT.Integracao.Relogios.Dimep
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public USUARIOS()
        {
            this.PERMISSOES = new HashSet<PERMISSOES>();
        }
    
        public int IDUSUARIO { get; set; }
        public string NOME { get; set; }
        public string SENHA { get; set; }
        public Nullable<bool> ATIVO { get; set; }
        public Nullable<bool> EXCLUIDO { get; set; }
    
        public virtual ICollection<PERMISSOES> PERMISSOES { get; set; }
    }
}
