//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralCliente
{
    using System;
    using System.Collections.Generic;
    
    public partial class cepbr_cidade
    {
        public cepbr_cidade()
        {
            this.cepbr_bairro = new HashSet<cepbr_bairro>();
            this.cepbr_endereco = new HashSet<cepbr_endereco>();
            this.Endereco = new HashSet<Endereco>();
        }
    
        public int ID { get; set; }
        public string cidade { get; set; }
        public string uf { get; set; }
        public string cod_ibge { get; set; }
        public double area { get; set; }
        public Nullable<int> IDCidadeCwork { get; set; }
        public Nullable<int> IDUF { get; set; }
    
        public virtual ICollection<cepbr_bairro> cepbr_bairro { get; set; }
        public virtual cepbr_estado cepbr_estado { get; set; }
        public virtual ICollection<cepbr_endereco> cepbr_endereco { get; set; }
        public virtual ICollection<Endereco> Endereco { get; set; }
    }
}
