//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralCliente
{
    using System;
    using System.Collections.Generic;
    
    public partial class cepbr_bairro
    {
        public cepbr_bairro()
        {
            this.cepbr_endereco = new HashSet<cepbr_endereco>();
        }
    
        public int ID { get; set; }
        public string bairro { get; set; }
        public Nullable<int> id_cidade { get; set; }
    
        public virtual cepbr_cidade cepbr_cidade { get; set; }
        public virtual ICollection<cepbr_endereco> cepbr_endereco { get; set; }
    }
}
