//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralCliente
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComunicadorServico
    {
        public ComunicadorServico()
        {
            this.Rep = new HashSet<Rep>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Codigo { get; set; }
        public Nullable<System.DateTime> Inchora { get; set; }
        public string Incusuario { get; set; }
        public Nullable<System.DateTime> Althora { get; set; }
        public string Altusuario { get; set; }
        public Nullable<int> IdComunicadorServidor { get; set; }
        public Nullable<int> IdCentroServico { get; set; }
        public string Descricao { get; set; }
        public string Observacao { get; set; }
    
        public virtual CentroServico CentroServico { get; set; }
        public virtual ICollection<Rep> Rep { get; set; }
        public virtual ComunicadorServidor ComunicadorServidor { get; set; }
    }
}
