//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralCliente
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email
    {
        public int ID { get; set; }
        public string email1 { get; set; }
        public int IDEmailTipo { get; set; }
        public int IDEntidade { get; set; }
    
        public virtual EmailTipo EmailTipo { get; set; }
        public virtual Entidade Entidade { get; set; }
    }
}
