//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralCliente
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParametroServComNet
    {
        public ParametroServComNet()
        {
            this.Cliente = new HashSet<Cliente>();
        }
    
        public int id { get; set; }
        public string ServidorInstancia { get; set; }
        public string BancoDados { get; set; }
        public string UsuarioBD { get; set; }
        public string SenhaBDBD { get; set; }
        public string Descricao { get; set; }
    
        public virtual ICollection<Cliente> Cliente { get; set; }
    }
}
