//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralCliente
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoStatus
    {
        public PedidoStatus()
        {
            this.Pedido = new HashSet<Pedido>();
        }
    
        public int ID { get; set; }
        public int Codigo { get; set; }
        public string Descricao { get; set; }
    
        public virtual ICollection<Pedido> Pedido { get; set; }
    }
}
