//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralCliente
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sistemas
    {
        public Sistemas()
        {
            this.Pedido = new HashSet<Pedido>();
            this.SistemaServico = new HashSet<SistemaServico>();
            this.SistemasRevenda = new HashSet<SistemasRevenda>();
            this.SistemaVersao = new HashSet<SistemaVersao>();
        }
    
        public int ID { get; set; }
        public int IDEmpresa { get; set; }
        public int Codigo { get; set; }
        public string Nome { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual ICollection<Pedido> Pedido { get; set; }
        public virtual ICollection<SistemaServico> SistemaServico { get; set; }
        public virtual ICollection<SistemasRevenda> SistemasRevenda { get; set; }
        public virtual ICollection<SistemaVersao> SistemaVersao { get; set; }
    }
}
