//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralCliente
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabelaPrecoDetalhe
    {
        public int ID { get; set; }
        public int IDTabelaPreco { get; set; }
        public Nullable<int> QuantCPFSMin { get; set; }
        public Nullable<int> QuantCPFSMax { get; set; }
        public Nullable<decimal> ValorUN { get; set; }
        public Nullable<decimal> ValorFechado { get; set; }
    
        public virtual TabelaPreco TabelaPreco { get; set; }
    }
}
