//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralCliente
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefone
    {
        public int ID { get; set; }
        public int IDTelefoneTipo { get; set; }
        public string CodigoPais { get; set; }
        public string DDD { get; set; }
        public string Numero { get; set; }
        public bool Principal { get; set; }
        public int IDEntidade { get; set; }
    
        public virtual Entidade Entidade { get; set; }
        public virtual TelefoneTipo TelefoneTipo { get; set; }
    }
}
