//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PontoWeb.EnviaSms {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmsRequest", Namespace="http://schemas.datacontract.org/2004/07/EnviaEmail")]
    [System.SerializableAttribute()]
    public partial class SmsRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> AgendamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CelularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensagemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrigemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PontoWeb.EnviaSms.EnumRemetenteSms RemetenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SeuNumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Agendamento {
            get {
                return this.AgendamentoField;
            }
            set {
                if ((this.AgendamentoField.Equals(value) != true)) {
                    this.AgendamentoField = value;
                    this.RaisePropertyChanged("Agendamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Celular {
            get {
                return this.CelularField;
            }
            set {
                if ((this.CelularField.Equals(value) != true)) {
                    this.CelularField = value;
                    this.RaisePropertyChanged("Celular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensagem {
            get {
                return this.MensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.MensagemField, value) != true)) {
                    this.MensagemField = value;
                    this.RaisePropertyChanged("Mensagem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Origem {
            get {
                return this.OrigemField;
            }
            set {
                if ((this.OrigemField.Equals(value) != true)) {
                    this.OrigemField = value;
                    this.RaisePropertyChanged("Origem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PontoWeb.EnviaSms.EnumRemetenteSms Remetente {
            get {
                return this.RemetenteField;
            }
            set {
                if ((this.RemetenteField.Equals(value) != true)) {
                    this.RemetenteField = value;
                    this.RaisePropertyChanged("Remetente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SeuNum {
            get {
                return this.SeuNumField;
            }
            set {
                if ((object.ReferenceEquals(this.SeuNumField, value) != true)) {
                    this.SeuNumField = value;
                    this.RaisePropertyChanged("SeuNum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnumRemetenteSms", Namespace="http://schemas.datacontract.org/2004/07/PonteAzul.Services.DAL.Enum")]
    public enum EnumRemetenteSms : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BNE = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EnviaSms.IWsEnviaSms")]
    public interface IWsEnviaSms {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsEnviaSms/EnviaSmsPadrao", ReplyAction="http://tempuri.org/IWsEnviaSms/EnviaSmsPadraoResponse")]
        void EnviaSmsPadrao(string seuNum, long celular, string mensagem, System.Nullable<System.DateTime> agendamento, int idOrigem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsEnviaSms/EnviaSmsPadrao", ReplyAction="http://tempuri.org/IWsEnviaSms/EnviaSmsPadraoResponse")]
        System.Threading.Tasks.Task EnviaSmsPadraoAsync(string seuNum, long celular, string mensagem, System.Nullable<System.DateTime> agendamento, int idOrigem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsEnviaSms/EnviaSMSDataSetPadrao", ReplyAction="http://tempuri.org/IWsEnviaSms/EnviaSMSDataSetPadraoResponse")]
        void EnviaSMSDataSetPadrao(System.Data.DataSet dsSms);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsEnviaSms/EnviaSMSDataSetPadrao", ReplyAction="http://tempuri.org/IWsEnviaSms/EnviaSMSDataSetPadraoResponse")]
        System.Threading.Tasks.Task EnviaSMSDataSetPadraoAsync(System.Data.DataSet dsSms);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsEnviaSms/EnviaSMSDataSet", ReplyAction="http://tempuri.org/IWsEnviaSms/EnviaSMSDataSetResponse")]
        void EnviaSMSDataSet(System.Data.DataSet dsSms);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsEnviaSms/EnviaSMSDataSet", ReplyAction="http://tempuri.org/IWsEnviaSms/EnviaSMSDataSetResponse")]
        System.Threading.Tasks.Task EnviaSMSDataSetAsync(System.Data.DataSet dsSms);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsEnviaSms/EnviaSmsRequest", ReplyAction="http://tempuri.org/IWsEnviaSms/EnviaSmsRequestResponse")]
        void EnviaSmsRequest(PontoWeb.EnviaSms.SmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsEnviaSms/EnviaSmsRequest", ReplyAction="http://tempuri.org/IWsEnviaSms/EnviaSmsRequestResponse")]
        System.Threading.Tasks.Task EnviaSmsRequestAsync(PontoWeb.EnviaSms.SmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsEnviaSms/EnviaSmsListRequest", ReplyAction="http://tempuri.org/IWsEnviaSms/EnviaSmsListRequestResponse")]
        void EnviaSmsListRequest(PontoWeb.EnviaSms.SmsRequest[] request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsEnviaSms/EnviaSmsListRequest", ReplyAction="http://tempuri.org/IWsEnviaSms/EnviaSmsListRequestResponse")]
        System.Threading.Tasks.Task EnviaSmsListRequestAsync(PontoWeb.EnviaSms.SmsRequest[] request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsEnviaSms/RecuperarStatusSms", ReplyAction="http://tempuri.org/IWsEnviaSms/RecuperarStatusSmsResponse")]
        System.Data.DataSet RecuperarStatusSms(string seuNum, System.Nullable<long> celular);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsEnviaSms/RecuperarStatusSms", ReplyAction="http://tempuri.org/IWsEnviaSms/RecuperarStatusSmsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> RecuperarStatusSmsAsync(string seuNum, System.Nullable<long> celular);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWsEnviaSmsChannel : PontoWeb.EnviaSms.IWsEnviaSms, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsEnviaSmsClient : System.ServiceModel.ClientBase<PontoWeb.EnviaSms.IWsEnviaSms>, PontoWeb.EnviaSms.IWsEnviaSms {
        
        public WsEnviaSmsClient() {
        }
        
        public WsEnviaSmsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsEnviaSmsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsEnviaSmsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsEnviaSmsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void EnviaSmsPadrao(string seuNum, long celular, string mensagem, System.Nullable<System.DateTime> agendamento, int idOrigem) {
            base.Channel.EnviaSmsPadrao(seuNum, celular, mensagem, agendamento, idOrigem);
        }
        
        public System.Threading.Tasks.Task EnviaSmsPadraoAsync(string seuNum, long celular, string mensagem, System.Nullable<System.DateTime> agendamento, int idOrigem) {
            return base.Channel.EnviaSmsPadraoAsync(seuNum, celular, mensagem, agendamento, idOrigem);
        }
        
        public void EnviaSMSDataSetPadrao(System.Data.DataSet dsSms) {
            base.Channel.EnviaSMSDataSetPadrao(dsSms);
        }
        
        public System.Threading.Tasks.Task EnviaSMSDataSetPadraoAsync(System.Data.DataSet dsSms) {
            return base.Channel.EnviaSMSDataSetPadraoAsync(dsSms);
        }
        
        public void EnviaSMSDataSet(System.Data.DataSet dsSms) {
            base.Channel.EnviaSMSDataSet(dsSms);
        }
        
        public System.Threading.Tasks.Task EnviaSMSDataSetAsync(System.Data.DataSet dsSms) {
            return base.Channel.EnviaSMSDataSetAsync(dsSms);
        }
        
        public void EnviaSmsRequest(PontoWeb.EnviaSms.SmsRequest request) {
            base.Channel.EnviaSmsRequest(request);
        }
        
        public System.Threading.Tasks.Task EnviaSmsRequestAsync(PontoWeb.EnviaSms.SmsRequest request) {
            return base.Channel.EnviaSmsRequestAsync(request);
        }
        
        public void EnviaSmsListRequest(PontoWeb.EnviaSms.SmsRequest[] request) {
            base.Channel.EnviaSmsListRequest(request);
        }
        
        public System.Threading.Tasks.Task EnviaSmsListRequestAsync(PontoWeb.EnviaSms.SmsRequest[] request) {
            return base.Channel.EnviaSmsListRequestAsync(request);
        }
        
        public System.Data.DataSet RecuperarStatusSms(string seuNum, System.Nullable<long> celular) {
            return base.Channel.RecuperarStatusSms(seuNum, celular);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> RecuperarStatusSmsAsync(string seuNum, System.Nullable<long> celular) {
            return base.Channel.RecuperarStatusSmsAsync(seuNum, celular);
        }
    }
}
