//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PontoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertasFuncionario
    {
        public int ID { get; set; }
        public int IDAlertas { get; set; }
        public int IDFuncionario { get; set; }
        public System.DateTime Ctl_Inicio { get; set; }
        public System.DateTime Ctl_Fim { get; set; }
    
        public virtual Alertas Alertas { get; set; }
        public virtual funcionario funcionario { get; set; }
    }
}
