//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PontoWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CentralClienteEntities1 : DbContext
    {
        public CentralClienteEntities1()
            : base("name=CentralClienteEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CentralLicencaOnline> CentralLicencaOnline { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Email> Email { get; set; }
        public virtual DbSet<EmailTipo> EmailTipo { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Endereco> Endereco { get; set; }
        public virtual DbSet<EnderecoTipo> EnderecoTipo { get; set; }
        public virtual DbSet<Entidade> Entidade { get; set; }
        public virtual DbSet<Pedido> Pedido { get; set; }
        public virtual DbSet<PedidoItem> PedidoItem { get; set; }
        public virtual DbSet<PedidoStatus> PedidoStatus { get; set; }
        public virtual DbSet<Revenda> Revenda { get; set; }
        public virtual DbSet<RevendaCliente> RevendaCliente { get; set; }
        public virtual DbSet<Servicos> Servicos { get; set; }
        public virtual DbSet<ServicosRevenda> ServicosRevenda { get; set; }
        public virtual DbSet<Sistemas> Sistemas { get; set; }
        public virtual DbSet<SistemaServico> SistemaServico { get; set; }
        public virtual DbSet<SistemaServicoTabelaPreco> SistemaServicoTabelaPreco { get; set; }
        public virtual DbSet<SistemasRevenda> SistemasRevenda { get; set; }
        public virtual DbSet<TabelaPreco> TabelaPreco { get; set; }
        public virtual DbSet<Telefone> Telefone { get; set; }
        public virtual DbSet<TelefoneTipo> TelefoneTipo { get; set; }
        public virtual DbSet<Unidade> Unidade { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    
        public virtual int p_ExecutaQuery(string parm, ObjectParameter retorno)
        {
            var parmParameter = parm != null ?
                new ObjectParameter("parm", parm) :
                new ObjectParameter("parm", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_ExecutaQuery", parmParameter, retorno);
        }
    
        public virtual int teste(string parm)
        {
            var parmParameter = parm != null ?
                new ObjectParameter("parm", parm) :
                new ObjectParameter("parm", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("teste", parmParameter);
        }
    }
}
