//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PontoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class exportacaocampos
    {
        public int id { get; set; }
        public int codigo { get; set; }
        public string tipo { get; set; }
        public Nullable<short> tamanho { get; set; }
        public Nullable<short> posicao { get; set; }
        public string delimitador { get; set; }
        public string qualificador { get; set; }
        public string texto { get; set; }
        public string cabecalho { get; set; }
        public string formatoevento { get; set; }
        public Nullable<int> zeroesquerda { get; set; }
        public Nullable<System.DateTime> incdata { get; set; }
        public Nullable<System.DateTime> inchora { get; set; }
        public string incusuario { get; set; }
        public Nullable<System.DateTime> altdata { get; set; }
        public Nullable<System.DateTime> althora { get; set; }
        public string altusuario { get; set; }
        public Nullable<int> idlayoutexportacao { get; set; }
    
        public virtual layoutexportacao layoutexportacao { get; set; }
    }
}
