//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PontoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class horariodetalhe
    {
        public int id { get; set; }
        public int codigo { get; set; }
        public Nullable<int> idhorario { get; set; }
        public Nullable<int> dia { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public string entrada_1 { get; set; }
        public string entrada_2 { get; set; }
        public string entrada_3 { get; set; }
        public string entrada_4 { get; set; }
        public string saida_1 { get; set; }
        public string saida_2 { get; set; }
        public string saida_3 { get; set; }
        public string saida_4 { get; set; }
        public string toleranciaantesent_1 { get; set; }
        public string toleranciaantesent_2 { get; set; }
        public string toleranciaantesent_3 { get; set; }
        public string toleranciaantesent_4 { get; set; }
        public string toleranciadepoisent_1 { get; set; }
        public string toleranciadepoisent_2 { get; set; }
        public string toleranciadepoisent_3 { get; set; }
        public string toleranciadepoisent_4 { get; set; }
        public string toleranciaantessai_1 { get; set; }
        public string toleranciaantessai_2 { get; set; }
        public string toleranciaantessai_3 { get; set; }
        public string toleranciaantessai_4 { get; set; }
        public string toleranciadepoissai_1 { get; set; }
        public string toleranciadepoissai_2 { get; set; }
        public string toleranciadepoissai_3 { get; set; }
        public string toleranciadepoissai_4 { get; set; }
        public string totaltrabalhadadiurna { get; set; }
        public string totaltrabalhadanoturna { get; set; }
        public string cargahorariamista { get; set; }
        public Nullable<int> flagfolga { get; set; }
        public Nullable<int> diadsr { get; set; }
        public Nullable<int> bcarregar { get; set; }
        public Nullable<System.DateTime> incdata { get; set; }
        public Nullable<System.DateTime> inchora { get; set; }
        public string incusuario { get; set; }
        public Nullable<System.DateTime> altdata { get; set; }
        public Nullable<System.DateTime> althora { get; set; }
        public string altusuario { get; set; }
        public Nullable<int> intervaloautomatico { get; set; }
        public Nullable<int> preassinaladas1 { get; set; }
        public Nullable<int> preassinaladas2 { get; set; }
        public Nullable<int> preassinaladas3 { get; set; }
        public Nullable<int> marcacargahorariamista { get; set; }
        public Nullable<int> idjornada { get; set; }
        public Nullable<int> neutro { get; set; }
        public string diadescricao { get; set; }
        public Nullable<int> CicloSequenciaIndice { get; set; }
        public System.DateTime Ctl_Inicio { get; set; }
        public System.DateTime Ctl_Fim { get; set; }
    
        public virtual horario horario { get; set; }
        public virtual jornada jornada { get; set; }
    }
}
