//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PontoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jornadaalternativa_view
    {
        public int id { get; set; }
        public Nullable<short> tipo { get; set; }
        public Nullable<int> identificacao { get; set; }
        public Nullable<System.DateTime> datainicial { get; set; }
        public Nullable<System.DateTime> datafinal { get; set; }
        public Nullable<System.DateTime> datacompensada { get; set; }
    }
}
