//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PontoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class marcacaoacesso
    {
        public int id { get; set; }
        public Nullable<int> codigo { get; set; }
        public Nullable<int> idfuncionario { get; set; }
        public Nullable<int> tipo { get; set; }
        public Nullable<System.DateTime> dtmar { get; set; }
        public Nullable<System.DateTime> hora { get; set; }
        public Nullable<int> idequipamento { get; set; }
        public string acesso { get; set; }
        public Nullable<System.DateTime> incdata { get; set; }
        public Nullable<System.DateTime> inchora { get; set; }
        public string incusuario { get; set; }
        public Nullable<System.DateTime> altdata { get; set; }
        public Nullable<System.DateTime> althora { get; set; }
        public string altusuario { get; set; }
    
        public virtual funcionario funcionario { get; set; }
    }
}
