//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PontoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class marcacao
    {
        public int id { get; set; }
        public Nullable<int> codigo { get; set; }
        public int idfuncionario { get; set; }
        public string dscodigo { get; set; }
        public string legenda { get; set; }
        public System.DateTime data { get; set; }
        public string dia { get; set; }
        public string entradaextra { get; set; }
        public string saidaextra { get; set; }
        public string ocorrencia { get; set; }
        public Nullable<int> idhorario { get; set; }
        public Nullable<int> idfechamentobh { get; set; }
        public Nullable<short> semcalculo { get; set; }
        public string ent_num_relogio_1 { get; set; }
        public string ent_num_relogio_2 { get; set; }
        public string ent_num_relogio_3 { get; set; }
        public string ent_num_relogio_4 { get; set; }
        public string ent_num_relogio_5 { get; set; }
        public string ent_num_relogio_6 { get; set; }
        public string ent_num_relogio_7 { get; set; }
        public string ent_num_relogio_8 { get; set; }
        public string sai_num_relogio_1 { get; set; }
        public string sai_num_relogio_2 { get; set; }
        public string sai_num_relogio_3 { get; set; }
        public string sai_num_relogio_4 { get; set; }
        public string sai_num_relogio_5 { get; set; }
        public string sai_num_relogio_6 { get; set; }
        public string sai_num_relogio_7 { get; set; }
        public string sai_num_relogio_8 { get; set; }
        public Nullable<short> naoentrarbanco { get; set; }
        public Nullable<short> naoentrarnacompensacao { get; set; }
        public string horascompensadas { get; set; }
        public Nullable<int> idcompensado { get; set; }
        public Nullable<short> naoconsiderarcafe { get; set; }
        public Nullable<short> dsr { get; set; }
        public Nullable<short> abonardsr { get; set; }
        public Nullable<short> totalizadoresalterados { get; set; }
        public Nullable<short> calchorasextrasdiurna { get; set; }
        public Nullable<short> calchorasextranoturna { get; set; }
        public Nullable<short> calchorasfaltas { get; set; }
        public Nullable<short> calchorasfaltanoturna { get; set; }
        public Nullable<System.DateTime> incdata { get; set; }
        public Nullable<System.DateTime> inchora { get; set; }
        public string incusuario { get; set; }
        public Nullable<System.DateTime> altdata { get; set; }
        public Nullable<System.DateTime> althora { get; set; }
        public string altusuario { get; set; }
        public Nullable<short> folga { get; set; }
        public string chave { get; set; }
        public Nullable<short> tipohoraextrafalta { get; set; }
        public byte[] campo01 { get; set; }
        public byte[] campo02 { get; set; }
        public byte[] campo03 { get; set; }
        public byte[] campo04 { get; set; }
        public byte[] campo05 { get; set; }
        public byte[] campo06 { get; set; }
        public byte[] campo07 { get; set; }
        public byte[] campo08 { get; set; }
        public byte[] campo09 { get; set; }
        public byte[] campo10 { get; set; }
        public byte[] campo11 { get; set; }
        public byte[] campo12 { get; set; }
        public byte[] campo13 { get; set; }
        public byte[] campo14 { get; set; }
        public byte[] campo15 { get; set; }
        public byte[] campo16 { get; set; }
        public byte[] campo17 { get; set; }
        public byte[] campo18 { get; set; }
        public byte[] campo19 { get; set; }
        public byte[] campo20 { get; set; }
        public byte[] campo21 { get; set; }
        public byte[] campo22 { get; set; }
        public byte[] campo23 { get; set; }
        public byte[] campo24 { get; set; }
        public byte[] campo25 { get; set; }
        public byte[] campo26 { get; set; }
        public Nullable<short> neutro { get; set; }
    
        public virtual compensacao compensacao { get; set; }
        public virtual fechamentobh fechamentobh { get; set; }
        public virtual funcionario funcionario { get; set; }
        public virtual horario horario { get; set; }
    }
}
