//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PontoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mudcodigofunc
    {
        public int id { get; set; }
        public int codigo { get; set; }
        public Nullable<System.DateTime> datainicial { get; set; }
        public Nullable<int> idfuncionario { get; set; }
        public string dscodigoantigo { get; set; }
        public string dscodigonovo { get; set; }
        public Nullable<int> tipohorario { get; set; }
        public Nullable<int> idhorarionormal { get; set; }
        public Nullable<int> iddepartamento { get; set; }
        public Nullable<int> idempresa { get; set; }
        public Nullable<System.DateTime> incdata { get; set; }
        public Nullable<System.DateTime> inchora { get; set; }
        public string incusuario { get; set; }
        public Nullable<System.DateTime> altdata { get; set; }
        public Nullable<System.DateTime> althora { get; set; }
        public string altusuario { get; set; }
        public System.DateTime Ctl_Inicio { get; set; }
        public System.DateTime Ctl_Fim { get; set; }
    
        public virtual departamento departamento { get; set; }
        public virtual empresa empresa { get; set; }
        public virtual funcionario funcionario { get; set; }
        public virtual horario horario { get; set; }
    }
}
