//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PontoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public Pedido()
        {
            this.PedidoItem = new HashSet<PedidoItem>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IDSistema { get; set; }
        public Nullable<int> IDRevenda { get; set; }
        public int IDCliente { get; set; }
        public int IDUsuario { get; set; }
        public string Observacao { get; set; }
        public System.DateTime Data { get; set; }
        public int IDPedidoStatus { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual PedidoStatus PedidoStatus { get; set; }
        public virtual Revenda Revenda { get; set; }
        public virtual Sistemas Sistemas { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<PedidoItem> PedidoItem { get; set; }
    }
}
