//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PontoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TelefoneTipo
    {
        public TelefoneTipo()
        {
            this.Telefone = new HashSet<Telefone>();
        }
    
        public int ID { get; set; }
        public int Codigo { get; set; }
        public string Descricao { get; set; }
    
        public virtual ICollection<Telefone> Telefone { get; set; }
    }
}
